package com.ddarungflow.admin.access;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationVersion;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class AdminRbacMigrationTest {
    @Test
    void appliesV11AfterV10BaselineWithSeedsLegacyAdminBackfillAndConstraints() {
        String url = "jdbc:h2:mem:admin-rbac-migration;MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        DriverManagerDataSource dataSource = new DriverManagerDataSource(url, "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                create table users (
                    id bigint generated by default as identity primary key,
                    created_at timestamp with time zone not null,
                    display_name varchar(100) not null,
                    email varchar(255), last_login_at timestamp with time zone,
                    provider varchar(50) not null, provider_user_id varchar(255) not null,
                    public_id uuid not null unique, role varchar(20) not null, updated_at timestamp with time zone not null
                )
                """);
        jdbc.execute("create table model_artifacts (id bigint generated by default as identity primary key)");
        jdbc.execute("""
                create table audit_events (
                    id bigint generated by default as identity primary key,
                    actor_user_id bigint not null, actor_role varchar(50) not null, action varchar(100) not null,
                    target_type varchar(100) not null, target_id varchar(100) not null, result varchar(50) not null,
                    reason_code varchar(100), correlation_id varchar(150) not null, occurred_at timestamp with time zone not null
                )
                """);
        jdbc.update("""
                insert into users (created_at, display_name, email, last_login_at, provider, provider_user_id,
                                   public_id, role, updated_at)
                values (current_timestamp, 'legacy-admin', null, null, 'google', 'legacy-admin', ?, 'ADMIN', current_timestamp)
                """, UUID.randomUUID());

        Flyway flyway = Flyway.configure().dataSource(dataSource).locations("classpath:db/migration")
                .baselineOnMigrate(true).baselineVersion(MigrationVersion.fromVersion("10")).load();
        flyway.migrate();

        assertThat(flyway.info().current().getVersion().getVersion()).isEqualTo("11");
        assertThat(jdbc.queryForObject("select count(*) from admin_roles", Integer.class)).isEqualTo(10);
        assertThat(jdbc.queryForObject("select count(*) from admin_permissions", Integer.class)).isEqualTo(30);
        assertThat(jdbc.queryForObject("select count(*) from admin_role_permissions", Integer.class)).isEqualTo(79);
        assertThat(jdbc.queryForObject("select role_code from admin_user_roles", String.class)).isEqualTo("SUPER_ADMIN");
        assertThat(jdbc.queryForObject("select assignment_version from admin_user_roles", Long.class)).isEqualTo(1L);
        assertThat(jdbc.queryForObject("select admin_role_version from users where role='ADMIN'", Long.class)).isEqualTo(1L);
        assertThat(jdbc.queryForObject("select reason from admin_user_roles", String.class)).contains("V11");

        Long userId = jdbc.queryForObject("select id from users where role='ADMIN'", Long.class);
        assertThatThrownBy(() -> jdbc.update("""
                insert into admin_user_roles (user_id, role_code, granted_by, granted_at, expires_at, reason, assignment_version)
                values (?, 'SUPER_ADMIN', ?, current_timestamp, null, '중복 역할', 1)
                """, userId, userId)).isInstanceOf(RuntimeException.class);
        assertThatThrownBy(() -> jdbc.update("""
                insert into admin_user_roles (user_id, role_code, granted_by, granted_at, expires_at, reason, assignment_version)
                values (999999, 'OPS_VIEWER', ?, current_timestamp, null, '없는 사용자', 1)
                """, userId)).isInstanceOf(RuntimeException.class);
        assertThatThrownBy(() -> jdbc.update("""
                insert into admin_user_roles (user_id, role_code, granted_by, granted_at, expires_at, reason, assignment_version)
                values (?, 'OPS_VIEWER', ?, current_timestamp, null, 'x', 1)
                """, userId, userId)).isInstanceOf(RuntimeException.class);
        assertThatThrownBy(() -> jdbc.update("""
                insert into admin_user_roles (user_id, role_code, granted_by, granted_at, expires_at, reason, assignment_version)
                values (?, 'OPS_VIEWER', ?, current_timestamp, dateadd('DAY', -1, current_timestamp), '잘못된 만료', 1)
                """, userId, userId)).isInstanceOf(RuntimeException.class);
        assertThatThrownBy(() -> jdbc.update("""
                insert into admin_user_roles (user_id, role_code, granted_by, granted_at, expires_at, reason, assignment_version)
                values (?, 'OPS_VIEWER', ?, current_timestamp, null, '음수 버전', -1)
                """, userId, userId)).isInstanceOf(RuntimeException.class);
    }
}
