package com.ddarungflow.admin.access;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationVersion;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.sql.Timestamp;
import java.time.Instant;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class AdminRbacMigrationTest {
    @Test
    void appliesV11ThroughV13AfterV10BaselineWithExpectedSchemaAndConstraints() {
        String url = "jdbc:h2:mem:admin-rbac-migration;MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        DriverManagerDataSource dataSource = new DriverManagerDataSource(url, "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                create table users (
                    id bigint generated by default as identity primary key,
                    created_at timestamp with time zone not null,
                    display_name varchar(100) not null,
                    email varchar(255), last_login_at timestamp with time zone,
                    provider varchar(50) not null, provider_user_id varchar(255) not null,
                    public_id uuid not null unique, role varchar(20) not null, updated_at timestamp with time zone not null
                )
                """);
        jdbc.execute("create table model_artifacts (id bigint generated by default as identity primary key)");
        jdbc.execute("create table saved_journeys (id bigint primary key)");
        jdbc.execute("""
                create table in_app_notifications (
                    id bigint generated by default as identity primary key,
                    user_id bigint not null,
                    dedup_key varchar(150) not null,
                    title varchar(200) not null,
                    message text not null,
                    created_at timestamp with time zone not null,
                    read_at timestamp with time zone
                )
                """);
        jdbc.execute("""
                create table audit_events (
                    id bigint generated by default as identity primary key,
                    actor_user_id bigint not null, actor_role varchar(50) not null, action varchar(100) not null,
                    target_type varchar(100) not null, target_id varchar(100) not null, result varchar(50) not null,
                    reason_code varchar(100), correlation_id varchar(150) not null, occurred_at timestamp with time zone not null
                )
                """);
        jdbc.update("""
                insert into users (created_at, display_name, email, last_login_at, provider, provider_user_id,
                                   public_id, role, updated_at)
                values (current_timestamp, 'legacy-admin', null, null, 'google', 'legacy-admin', ?, 'ADMIN', current_timestamp)
                """, UUID.randomUUID());
        jdbc.update("insert into saved_journeys (id) values (10)");
        jdbc.update("""
                insert into in_app_notifications (user_id, dedup_key, title, message, created_at)
                values (1, 'legacy-notification', 'legacy', 'kept', current_timestamp)
                """);

        Flyway flyway = Flyway.configure().dataSource(dataSource).locations("classpath:db/migration")
                .baselineOnMigrate(true).baselineVersion(MigrationVersion.fromVersion("10")).load();
        flyway.migrate();

        assertThat(flyway.info().current().getVersion().getVersion()).isEqualTo("13");
        assertThat(jdbc.queryForObject("select count(*) from admin_roles", Integer.class)).isEqualTo(10);
        assertThat(jdbc.queryForObject("select count(*) from admin_permissions", Integer.class)).isEqualTo(30);
        assertThat(jdbc.queryForObject("select count(*) from admin_role_permissions", Integer.class)).isEqualTo(79);
        assertThat(jdbc.queryForObject("select role_code from admin_user_roles", String.class)).isEqualTo("SUPER_ADMIN");
        assertThat(jdbc.queryForObject("select assignment_version from admin_user_roles", Long.class)).isEqualTo(1L);
        assertThat(jdbc.queryForObject("select admin_role_version from users where role='ADMIN'", Long.class)).isEqualTo(1L);
        assertThat(jdbc.queryForObject("select reason from admin_user_roles", String.class)).contains("V11");

        Long userId = jdbc.queryForObject("select id from users where role='ADMIN'", Long.class);
        assertThatThrownBy(() -> jdbc.update("""
                insert into admin_user_roles (user_id, role_code, granted_by, granted_at, expires_at, reason, assignment_version)
                values (?, 'SUPER_ADMIN', ?, current_timestamp, null, '중복 역할', 1)
                """, userId, userId)).isInstanceOf(RuntimeException.class);
        assertThatThrownBy(() -> jdbc.update("""
                insert into admin_user_roles (user_id, role_code, granted_by, granted_at, expires_at, reason, assignment_version)
                values (999999, 'OPS_VIEWER', ?, current_timestamp, null, '없는 사용자', 1)
                """, userId)).isInstanceOf(RuntimeException.class);
        assertThatThrownBy(() -> jdbc.update("""
                insert into admin_user_roles (user_id, role_code, granted_by, granted_at, expires_at, reason, assignment_version)
                values (?, 'OPS_VIEWER', ?, current_timestamp, null, 'x', 1)
                """, userId, userId)).isInstanceOf(RuntimeException.class);
        assertThatThrownBy(() -> jdbc.update("""
                insert into admin_user_roles (user_id, role_code, granted_by, granted_at, expires_at, reason, assignment_version)
                values (?, 'OPS_VIEWER', ?, current_timestamp, dateadd('DAY', -1, current_timestamp), '잘못된 만료', 1)
                """, userId, userId)).isInstanceOf(RuntimeException.class);
        assertThatThrownBy(() -> jdbc.update("""
                insert into admin_user_roles (user_id, role_code, granted_by, granted_at, expires_at, reason, assignment_version)
                values (?, 'OPS_VIEWER', ?, current_timestamp, null, '음수 버전', -1)
                """, userId, userId)).isInstanceOf(RuntimeException.class);

        assertThat(jdbc.queryForList("""
                select column_name from information_schema.columns
                where table_schema = 'PUBLIC' and table_name = 'CONSUMER_RECHECK_SUBSCRIPTIONS'
                """, String.class)).containsExactlyInAnyOrder(
                "ID", "PUBLIC_ID", "USER_ID", "KIND", "SAVED_JOURNEY_ID", "INPUT_JSON",
                "DEPARTURE_AT", "NOTIFY_AT", "STATUS", "DEDUP_KEY", "CREATED_AT");
        assertThat(jdbc.queryForObject("""
                select count(*) from information_schema.indexes
                where table_schema = 'PUBLIC' and table_name = 'CONSUMER_RECHECK_SUBSCRIPTIONS'
                  and index_name in ('IX_CONSUMER_RECHECK_SUBSCRIPTIONS_DUE',
                                     'IX_CONSUMER_RECHECK_SUBSCRIPTIONS_USER_CREATED')
                """, Integer.class)).isEqualTo(2);
        assertThat(jdbc.queryForObject("select count(*) from in_app_notifications", Integer.class)).isEqualTo(1);
        assertThat(jdbc.queryForObject("""
                select count(*) from information_schema.columns
                where table_schema = 'PUBLIC' and table_name = 'IN_APP_NOTIFICATIONS'
                  and column_name in ('ACTION_TYPE', 'ACTION_REF') and is_nullable = 'YES'
                """, Integer.class)).isEqualTo(2);

        Timestamp departure = Timestamp.from(Instant.parse("2026-09-02T12:00:00Z"));
        Timestamp notify = Timestamp.from(Instant.parse("2026-09-02T11:45:00Z"));
        jdbc.update("""
                insert into consumer_recheck_subscriptions
                    (public_id, user_id, kind, saved_journey_id, input_json, departure_at, notify_at, status, dedup_key, created_at)
                values ('plan-1', 1, 'PLAN_RECHECK', 10, null, ?, ?, 'ACTIVE', 'dedup-plan', current_timestamp)
                """, departure, notify);
        jdbc.update("""
                insert into consumer_recheck_subscriptions
                    (public_id, user_id, kind, saved_journey_id, input_json, departure_at, notify_at, status, dedup_key, created_at)
                values ('search-1', 1, 'SEARCH_RECHECK', null, '{}', ?, ?, 'ACTIVE', 'dedup-search', current_timestamp)
                """, departure, notify);

        assertThatThrownBy(() -> jdbc.update("""
                insert into consumer_recheck_subscriptions
                    (public_id, user_id, kind, saved_journey_id, input_json, departure_at, notify_at, status, dedup_key, created_at)
                values ('invalid-payload', 1, 'PLAN_RECHECK', null, '{}', ?, ?, 'ACTIVE', 'dedup-invalid', current_timestamp)
                """, departure, notify)).isInstanceOf(RuntimeException.class);
        assertThatThrownBy(() -> jdbc.update("""
                insert into consumer_recheck_subscriptions
                    (public_id, user_id, kind, saved_journey_id, input_json, departure_at, notify_at, status, dedup_key, created_at)
                values ('invalid-time', 1, 'SEARCH_RECHECK', null, '{}', ?, ?, 'ACTIVE', 'dedup-time', current_timestamp)
                """, notify, departure)).isInstanceOf(RuntimeException.class);
        assertThatThrownBy(() -> jdbc.update("""
                insert into consumer_recheck_subscriptions
                    (public_id, user_id, kind, saved_journey_id, input_json, departure_at, notify_at, status, dedup_key, created_at)
                values ('duplicate-dedup', 1, 'SEARCH_RECHECK', null, '{}', ?, ?, 'ACTIVE', 'dedup-search', current_timestamp)
                """, departure, notify)).isInstanceOf(RuntimeException.class);
        assertThatThrownBy(() -> jdbc.update("""
                insert into consumer_recheck_subscriptions
                    (public_id, user_id, kind, saved_journey_id, input_json, departure_at, notify_at, status, dedup_key, created_at)
                values ('invalid-status', 1, 'SEARCH_RECHECK', null, '{}', ?, ?, 'PENDING', 'dedup-status', current_timestamp)
                """, departure, notify)).isInstanceOf(RuntimeException.class);

        jdbc.update("delete from saved_journeys where id = 10");
        assertThat(jdbc.queryForObject("""
                select count(*) from consumer_recheck_subscriptions where kind = 'PLAN_RECHECK'
                """, Integer.class)).isZero();
    }
}
