CREATE TABLE journey_decisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id varchar(36) NOT NULL,
    user_id bigint NOT NULL,
    revision integer NOT NULL,
    status varchar(40) NOT NULL,
    normalized_intent_json text NOT NULL,
    contract_versions text NOT NULL,
    generated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT uk_journey_decisions_public_revision UNIQUE (public_id, revision),
    CONSTRAINT fk_journey_decisions_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX ix_journey_decisions_user_expires ON journey_decisions (user_id, expires_at);
CREATE INDEX ix_journey_decisions_user_public_revision ON journey_decisions (user_id, public_id, revision DESC);
CREATE INDEX ix_journey_decisions_expires ON journey_decisions (expires_at);

CREATE TABLE journey_candidates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id bigint NOT NULL,
    candidate_key varchar(100) NOT NULL,
    archetype varchar(40) NOT NULL,
    snapshot_json text NOT NULL,
    provenance_json text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT uk_journey_candidate_key UNIQUE (decision_id, candidate_key),
    CONSTRAINT fk_journey_candidates_decision FOREIGN KEY (decision_id) REFERENCES journey_decisions(id) ON DELETE CASCADE
);

CREATE TABLE saved_journeys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id varchar(36) NOT NULL,
    user_id bigint NOT NULL,
    display_name varchar(200) NOT NULL,
    replay_input_json text NOT NULL,
    duplicate_key varchar(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT uk_saved_journeys_public_id UNIQUE (public_id),
    CONSTRAINT uk_saved_journeys_user_duplicate UNIQUE (user_id, duplicate_key),
    CONSTRAINT fk_saved_journeys_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX ix_saved_journeys_user_created ON saved_journeys (user_id, created_at DESC);

CREATE TABLE saved_journey_idempotency_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    idempotency_key varchar(128) NOT NULL,
    request_hash varchar(64) NOT NULL,
    saved_journey_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT uk_saved_journey_idempotency_keys_user_key UNIQUE (user_id, idempotency_key),
    CONSTRAINT fk_saved_journey_idempotency_keys_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_saved_journey_idempotency_keys_saved_journey FOREIGN KEY (saved_journey_id) REFERENCES saved_journeys(id) ON DELETE CASCADE
);

CREATE INDEX ix_saved_journey_idempotency_keys_user_key ON saved_journey_idempotency_keys (user_id, idempotency_key);
