ALTER TABLE users ADD COLUMN admin_role_version bigint NOT NULL DEFAULT 0;

CREATE TABLE admin_roles (
    code varchar(50) PRIMARY KEY,
    display_name varchar(100) NOT NULL,
    description varchar(255) NOT NULL,
    system_role boolean NOT NULL,
    protected_role boolean NOT NULL,
    default_console varchar(20) NOT NULL,
    CONSTRAINT admin_roles_default_console_check CHECK (default_console IN ('OPS', 'MODEL', 'SYSTEM'))
);

CREATE TABLE admin_permissions (
    code varchar(80) PRIMARY KEY,
    category varchar(30) NOT NULL,
    description varchar(255) NOT NULL,
    CONSTRAINT admin_permissions_category_check CHECK (category IN ('OPS', 'DATA', 'MODEL', 'GOVERNANCE'))
);

CREATE TABLE admin_role_permissions (
    role_code varchar(50) NOT NULL,
    permission_code varchar(80) NOT NULL,
    CONSTRAINT pk_admin_role_permissions PRIMARY KEY (role_code, permission_code),
    CONSTRAINT fk_admin_role_permissions_role FOREIGN KEY (role_code) REFERENCES admin_roles(code),
    CONSTRAINT fk_admin_role_permissions_permission FOREIGN KEY (permission_code) REFERENCES admin_permissions(code)
);

CREATE TABLE admin_user_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    role_code varchar(50) NOT NULL,
    granted_by bigint NOT NULL,
    granted_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    reason varchar(200) NOT NULL,
    assignment_version bigint NOT NULL,
    CONSTRAINT uk_admin_user_roles_user_role UNIQUE (user_id, role_code),
    CONSTRAINT fk_admin_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_admin_user_roles_role FOREIGN KEY (role_code) REFERENCES admin_roles(code),
    CONSTRAINT fk_admin_user_roles_granted_by FOREIGN KEY (granted_by) REFERENCES users(id),
    CONSTRAINT admin_user_roles_reason_check CHECK (char_length(trim(reason)) BETWEEN 2 AND 200),
    CONSTRAINT admin_user_roles_expiry_check CHECK (expires_at IS NULL OR expires_at > granted_at),
    CONSTRAINT admin_user_roles_version_check CHECK (assignment_version >= 0)
);

CREATE INDEX ix_admin_user_roles_user_expiry ON admin_user_roles (user_id, expires_at);
CREATE INDEX ix_admin_user_roles_role_expiry ON admin_user_roles (role_code, expires_at);
CREATE INDEX ix_admin_user_roles_granted_by ON admin_user_roles (granted_by);
CREATE INDEX ix_admin_role_permissions_permission ON admin_role_permissions (permission_code);

INSERT INTO admin_roles (code, display_name, description, system_role, protected_role, default_console) VALUES
    ('OPS_VIEWER', '수급 현황 조회', '상황판·지도·후보·분석 읽기', true, false, 'OPS'),
    ('OPS_OPERATOR', '운영 검토 수행', '관찰 대상·메모·리포트 관리', true, false, 'OPS'),
    ('OPS_MANAGER', '운영 기준 관리', '운영 임계값·후보 정책 승인', true, false, 'OPS'),
    ('DATA_ANALYST', '데이터 품질·분석', '데이터 상태·Export·모델 지표 읽기', true, false, 'OPS'),
    ('MODEL_ENGINEER', '모델 준비·검증', 'artifact 등록·validate', true, false, 'MODEL'),
    ('MODEL_APPROVER', '모델 승인·배포', 'approve/reject·activate·rollback', true, false, 'MODEL'),
    ('SUPPORT_OPERATOR', '사용자 문의 처리', 'Q&A 읽기·답변·상태·숨김', true, false, 'SYSTEM'),
    ('AUDITOR', '변경 이력 검토', '감사 로그 읽기 전용', true, false, 'SYSTEM'),
    ('ACCESS_ADMIN', '세부 역할 관리', '역할 부여·회수·보호 규칙', true, true, 'SYSTEM'),
    ('SUPER_ADMIN', '비상 복구·최종 관리', '모든 권한, 강한 보호·감사', true, true, 'OPS');

INSERT INTO admin_permissions (code, category, description) VALUES
    ('OPS_DASHBOARD_READ', 'OPS', '운영 상황판 읽기'),
    ('OPS_RISK_MAP_READ', 'OPS', '운영 위험 지도 읽기'),
    ('OPS_CANDIDATE_READ', 'OPS', '운영 후보 읽기'),
    ('OPS_CANDIDATE_MANAGE', 'OPS', '운영 후보 관리'),
    ('OPS_ANALYSIS_READ', 'OPS', '운영 분석 읽기'),
    ('OPS_THRESHOLD_MANAGE', 'OPS', '운영 임계값 관리'),
    ('OPS_REPORT_EXPORT', 'OPS', '운영 리포트 내보내기'),
    ('OPS_SCENARIO_READ', 'OPS', '운영 시나리오 읽기'),
    ('DATA_STATUS_READ', 'DATA', '데이터 상태 읽기'),
    ('DATA_EXPORT_REQUEST', 'DATA', '데이터 내보내기 요청'),
    ('DATA_EXPORT_DOWNLOAD', 'DATA', '데이터 내보내기 다운로드'),
    ('DATA_ISSUE_ACKNOWLEDGE', 'DATA', '데이터 이슈 확인'),
    ('MODEL_METRICS_READ', 'MODEL', '모델 지표 읽기'),
    ('MODEL_DIAGNOSTICS_READ', 'MODEL', '모델 진단 읽기'),
    ('MODEL_ARTIFACT_REGISTER', 'MODEL', '모델 artifact 등록'),
    ('MODEL_VALIDATE', 'MODEL', '모델 검증'),
    ('MODEL_APPROVE', 'MODEL', '모델 승인 또는 거부'),
    ('MODEL_ACTIVATE', 'MODEL', '모델 활성화'),
    ('MODEL_ROLLBACK', 'MODEL', '모델 롤백'),
    ('MODEL_RELEASE_READ', 'MODEL', '모델 릴리스 읽기'),
    ('QNA_READ', 'GOVERNANCE', 'Q&A 읽기'),
    ('QNA_ANSWER', 'GOVERNANCE', 'Q&A 답변'),
    ('QNA_STATE_CHANGE', 'GOVERNANCE', 'Q&A 상태 변경'),
    ('QNA_HIDE', 'GOVERNANCE', 'Q&A 숨김'),
    ('AUDIT_READ', 'GOVERNANCE', '감사 로그 읽기'),
    ('ACCESS_READ', 'GOVERNANCE', '권한 구조 읽기'),
    ('ACCESS_ASSIGN', 'GOVERNANCE', '관리자 역할 부여'),
    ('ACCESS_REVOKE', 'GOVERNANCE', '관리자 역할 회수'),
    ('SYSTEM_STATUS_READ', 'GOVERNANCE', '시스템 상태 읽기'),
    ('AI_OPS_READ', 'GOVERNANCE', 'AI 운영 상태 읽기');

INSERT INTO admin_role_permissions (role_code, permission_code) VALUES
    ('OPS_VIEWER', 'OPS_DASHBOARD_READ'), ('OPS_VIEWER', 'OPS_RISK_MAP_READ'),
    ('OPS_VIEWER', 'OPS_CANDIDATE_READ'), ('OPS_VIEWER', 'OPS_ANALYSIS_READ'),
    ('OPS_VIEWER', 'DATA_STATUS_READ'),
    ('OPS_OPERATOR', 'OPS_DASHBOARD_READ'), ('OPS_OPERATOR', 'OPS_RISK_MAP_READ'),
    ('OPS_OPERATOR', 'OPS_CANDIDATE_READ'), ('OPS_OPERATOR', 'OPS_ANALYSIS_READ'),
    ('OPS_OPERATOR', 'DATA_STATUS_READ'), ('OPS_OPERATOR', 'OPS_CANDIDATE_MANAGE'),
    ('OPS_OPERATOR', 'OPS_REPORT_EXPORT'),
    ('OPS_MANAGER', 'OPS_DASHBOARD_READ'), ('OPS_MANAGER', 'OPS_RISK_MAP_READ'),
    ('OPS_MANAGER', 'OPS_CANDIDATE_READ'), ('OPS_MANAGER', 'OPS_ANALYSIS_READ'),
    ('OPS_MANAGER', 'DATA_STATUS_READ'), ('OPS_MANAGER', 'OPS_CANDIDATE_MANAGE'),
    ('OPS_MANAGER', 'OPS_REPORT_EXPORT'), ('OPS_MANAGER', 'OPS_THRESHOLD_MANAGE'),
    ('OPS_MANAGER', 'OPS_SCENARIO_READ'),
    ('DATA_ANALYST', 'DATA_STATUS_READ'), ('DATA_ANALYST', 'DATA_EXPORT_REQUEST'),
    ('DATA_ANALYST', 'DATA_EXPORT_DOWNLOAD'), ('DATA_ANALYST', 'DATA_ISSUE_ACKNOWLEDGE'),
    ('DATA_ANALYST', 'OPS_ANALYSIS_READ'), ('DATA_ANALYST', 'MODEL_METRICS_READ'),
    ('DATA_ANALYST', 'MODEL_DIAGNOSTICS_READ'),
    ('MODEL_ENGINEER', 'MODEL_METRICS_READ'), ('MODEL_ENGINEER', 'MODEL_DIAGNOSTICS_READ'),
    ('MODEL_ENGINEER', 'MODEL_ARTIFACT_REGISTER'), ('MODEL_ENGINEER', 'MODEL_VALIDATE'),
    ('MODEL_ENGINEER', 'MODEL_RELEASE_READ'),
    ('MODEL_APPROVER', 'MODEL_METRICS_READ'), ('MODEL_APPROVER', 'MODEL_DIAGNOSTICS_READ'),
    ('MODEL_APPROVER', 'MODEL_APPROVE'), ('MODEL_APPROVER', 'MODEL_ACTIVATE'),
    ('MODEL_APPROVER', 'MODEL_ROLLBACK'), ('MODEL_APPROVER', 'MODEL_RELEASE_READ'),
    ('SUPPORT_OPERATOR', 'QNA_READ'), ('SUPPORT_OPERATOR', 'QNA_ANSWER'),
    ('SUPPORT_OPERATOR', 'QNA_STATE_CHANGE'), ('SUPPORT_OPERATOR', 'QNA_HIDE'),
    ('AUDITOR', 'AUDIT_READ'), ('AUDITOR', 'SYSTEM_STATUS_READ'),
    ('ACCESS_ADMIN', 'ACCESS_READ'), ('ACCESS_ADMIN', 'ACCESS_ASSIGN'),
    ('ACCESS_ADMIN', 'ACCESS_REVOKE'), ('ACCESS_ADMIN', 'AUDIT_READ');

INSERT INTO admin_role_permissions (role_code, permission_code)
SELECT 'SUPER_ADMIN', code FROM admin_permissions;

INSERT INTO admin_user_roles
    (user_id, role_code, granted_by, granted_at, expires_at, reason, assignment_version)
SELECT id, 'SUPER_ADMIN', id, CURRENT_TIMESTAMP, NULL, 'V11 기존 ADMIN 안전 이관', 1
FROM users
WHERE role = 'ADMIN';

UPDATE users SET admin_role_version = 1 WHERE role = 'ADMIN';

ALTER TABLE model_artifacts ADD COLUMN validated_by_user_id bigint;
ALTER TABLE model_artifacts ADD CONSTRAINT fk_model_artifacts_validated_by
    FOREIGN KEY (validated_by_user_id) REFERENCES users(id);

ALTER TABLE audit_events ADD COLUMN actor_role_codes varchar(500);
ALTER TABLE audit_events ADD COLUMN reason varchar(200);
UPDATE audit_events SET actor_role_codes = actor_role;
ALTER TABLE audit_events ALTER COLUMN actor_role_codes SET NOT NULL;
