CREATE TABLE consumer_recheck_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id varchar(36) NOT NULL,
    user_id bigint NOT NULL,
    kind varchar(20) NOT NULL,
    saved_journey_id bigint,
    input_json text,
    departure_at timestamp with time zone NOT NULL,
    notify_at timestamp with time zone NOT NULL,
    status varchar(20) NOT NULL,
    dedup_key varchar(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT uk_consumer_recheck_subscriptions_public_id UNIQUE (public_id),
    CONSTRAINT uk_consumer_recheck_subscriptions_user_dedup UNIQUE (user_id, dedup_key),
    CONSTRAINT fk_consumer_recheck_subscriptions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_consumer_recheck_subscriptions_saved_journey
        FOREIGN KEY (saved_journey_id) REFERENCES saved_journeys(id) ON DELETE CASCADE,
    CONSTRAINT ck_consumer_recheck_subscriptions_kind
        CHECK (kind IN ('PLAN_RECHECK', 'SEARCH_RECHECK')),
    CONSTRAINT ck_consumer_recheck_subscriptions_payload
        CHECK (
            (kind = 'PLAN_RECHECK' AND saved_journey_id IS NOT NULL AND input_json IS NULL)
            OR (kind = 'SEARCH_RECHECK' AND saved_journey_id IS NULL AND input_json IS NOT NULL)
        ),
    CONSTRAINT ck_consumer_recheck_subscriptions_notify_at
        CHECK (notify_at <= departure_at),
    CONSTRAINT ck_consumer_recheck_subscriptions_status
        CHECK (status IN ('ACTIVE', 'DELIVERED', 'CANCELLED', 'FAILED'))
);

CREATE INDEX ix_consumer_recheck_subscriptions_due
    ON consumer_recheck_subscriptions (status, notify_at);
CREATE INDEX ix_consumer_recheck_subscriptions_user_created
    ON consumer_recheck_subscriptions (user_id, created_at DESC);

ALTER TABLE in_app_notifications ADD COLUMN action_type varchar(50);
ALTER TABLE in_app_notifications ADD COLUMN action_ref varchar(100);
