CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    display_name varchar(100) NOT NULL,
    email varchar(255), last_login_at timestamp(6) with time zone,
    provider varchar(50) NOT NULL, provider_user_id varchar(255) NOT NULL,
    public_id uuid NOT NULL, role varchar(20) NOT NULL, updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT uk_users_provider_provider_user_id UNIQUE (provider, provider_user_id),
    CONSTRAINT uk_users_public_id UNIQUE (public_id)
);

CREATE TABLE stations (
    station_id varchar(50) PRIMARY KEY, active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL, latitude numeric(10,7) NOT NULL,
    longitude numeric(10,7) NOT NULL, name varchar(100) NOT NULL,
    station_number varchar(20), updated_at timestamp(6) with time zone NOT NULL
);
CREATE TABLE station_inventory_current (
    station_id varchar(50) PRIMARY KEY, available_bike_count integer,
    collected_at timestamp(6) with time zone, inventory_status varchar(20) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT station_inventory_current_inventory_status_check CHECK (inventory_status IN ('NORMAL', 'DELAYED', 'MISSING', 'UNAVAILABLE'))
);
CREATE TABLE prediction_batches (
    batch_id uuid PRIMARY KEY, created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL, feature_as_of timestamp(6) with time zone NOT NULL,
    generated_at timestamp(6) with time zone NOT NULL, model_version varchar(100) NOT NULL,
    pipeline_run_id varchar(255), publish_status varchar(20) NOT NULL,
    published_at timestamp(6) with time zone,
    CONSTRAINT prediction_batches_publish_status_check CHECK (publish_status IN ('STAGING', 'ACTIVE', 'REJECTED', 'EXPIRED'))
);
CREATE TABLE station_predictions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, batch_id uuid NOT NULL,
    station_id varchar(50) NOT NULL, prediction_target_at timestamp(6) with time zone NOT NULL,
    horizon_minutes integer NOT NULL, at_least_1_probability numeric(8,7) NOT NULL,
    at_least_2_probability numeric(8,7) NOT NULL, at_least_3_probability numeric(8,7) NOT NULL,
    at_least_4_probability numeric(8,7) NOT NULL, at_least_5_probability numeric(8,7) NOT NULL,
    prediction_status varchar(20) NOT NULL, created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_station_predictions_batch_station_target UNIQUE (batch_id, station_id, prediction_target_at),
    CONSTRAINT fk_station_predictions_batch FOREIGN KEY (batch_id) REFERENCES prediction_batches(batch_id)
);

CREATE TABLE audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_user_id bigint NOT NULL,
    actor_role varchar(50) NOT NULL, action varchar(100) NOT NULL, target_type varchar(100) NOT NULL,
    target_id varchar(100) NOT NULL, result varchar(50) NOT NULL, reason_code varchar(100),
    correlation_id varchar(150) NOT NULL, occurred_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT audit_events_actor_role_check CHECK (actor_role IN ('USER', 'ADMIN')),
    CONSTRAINT audit_events_result_check CHECK (result IN ('SUCCESS', 'FAILURE')),
    CONSTRAINT uk_audit_event_key UNIQUE (correlation_id, action, target_type, target_id)
);
CREATE TABLE export_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, requester_user_id bigint NOT NULL,
    source varchar(32) NOT NULL, format varchar(16) NOT NULL, purpose varchar(256), status varchar(20) NOT NULL,
    row_count bigint, requested_at timestamp(6) with time zone NOT NULL, completed_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone, failure_reason_code varchar(64),
    CONSTRAINT export_requests_source_check CHECK (source IN ('CURATED', 'QUARANTINE_NORMALIZED')),
    CONSTRAINT export_requests_format_check CHECK (format IN ('CSV', 'PARQUET')),
    CONSTRAINT export_requests_status_check CHECK (status IN ('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', 'EXPIRED'))
);

CREATE TABLE model_artifacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version varchar(100) NOT NULL,
    trainer_user_id bigint NOT NULL, artifact_key varchar(512) NOT NULL, sha256 varchar(64) NOT NULL,
    code_commit varchar(40) NOT NULL, data_manifest_hash varchar(64) NOT NULL,
    config_hash varchar(64) NOT NULL, feature_schema_version varchar(64) NOT NULL,
    state varchar(20) NOT NULL, created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT model_artifacts_state_check CHECK (state IN ('DRAFT', 'VALIDATED', 'APPROVED', 'REJECTED', 'ACTIVE', 'RETIRED')),
    CONSTRAINT uk_model_artifacts_version UNIQUE (version), CONSTRAINT uk_model_artifacts_sha256 UNIQUE (sha256)
);
CREATE TABLE model_evaluations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, model_id bigint NOT NULL,
    horizon_minutes integer NOT NULL, required_bike_count integer NOT NULL, sample_count bigint NOT NULL,
    brier_score numeric(12,10) NOT NULL, shortage_recall numeric(12,10) NOT NULL,
    calibration_error numeric(12,10) NOT NULL, coverage numeric(12,10) NOT NULL,
    monotonicity_violations integer NOT NULL,
    CONSTRAINT uk_model_evaluations_model_horizon_required UNIQUE (model_id, horizon_minutes, required_bike_count)
);
CREATE TABLE model_uploads (
    id uuid PRIMARY KEY, requested_by_user_id bigint NOT NULL, object_key varchar(512) NOT NULL,
    expected_sha256 varchar(64) NOT NULL, max_bytes bigint NOT NULL, status varchar(20) NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL, completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT model_uploads_status_check CHECK (status IN ('CREATED', 'COMPLETED', 'FAILED', 'EXPIRED')),
    CONSTRAINT uk_model_uploads_object_key UNIQUE (object_key)
);
CREATE TABLE activation_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, candidate_model_id bigint NOT NULL,
    previous_model_id bigint, actor_user_id bigint NOT NULL, status varchar(50) NOT NULL,
    correlation_id varchar(150) NOT NULL, started_at timestamp(6) with time zone NOT NULL,
    finished_at timestamp(6) with time zone, failure_reason_code varchar(100),
    CONSTRAINT activation_attempts_status_check CHECK (status IN ('STARTED', 'SUCCEEDED', 'FAILED_COMPENSATED', 'COMPENSATION_FAILED')),
    CONSTRAINT uk_activation_attempt_correlation UNIQUE (correlation_id)
);
CREATE TABLE model_artifact_purge_marks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, artifact_id bigint NOT NULL,
    state varchar(20) NOT NULL, marked_at timestamp(6) with time zone NOT NULL, reason varchar(256),
    CONSTRAINT model_artifact_purge_marks_state_check CHECK (state IN ('DRAFT', 'VALIDATED', 'APPROVED', 'REJECTED', 'ACTIVE', 'RETIRED')),
    CONSTRAINT uk_model_artifact_purge_marks_artifact UNIQUE (artifact_id)
);

CREATE TABLE subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL,
    plan varchar(255) NOT NULL, status varchar(255) NOT NULL,
    starts_at timestamp(6) with time zone NOT NULL, ends_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT subscriptions_plan_check CHECK (plan IN ('PREMIUM_MONTHLY_30D', 'PREMIUM_YEARLY_365D')),
    CONSTRAINT subscriptions_status_check CHECK (status IN ('ACTIVE', 'EXPIRED')),
    CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL,
    order_id varchar(80) NOT NULL, plan varchar(255) NOT NULL, amount integer NOT NULL,
    currency varchar(3) NOT NULL, status varchar(255) NOT NULL, created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT payments_plan_check CHECK (plan IN ('PREMIUM_MONTHLY_30D', 'PREMIUM_YEARLY_365D')),
    CONSTRAINT payments_status_check CHECK (status IN ('READY', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELED', 'EXPIRED')),
    CONSTRAINT uk_payments_order_id UNIQUE (order_id),
    CONSTRAINT fk_payments_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE payment_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, provider varchar(20) NOT NULL,
    event_id varchar(120) NOT NULL, outcome varchar(255) NOT NULL,
    received_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT payment_events_outcome_check CHECK (outcome IN ('ACTIVE', 'VERIFICATION_FAILED')),
    CONSTRAINT uk_payment_event_provider_event UNIQUE (provider, event_id)
);

CREATE TABLE qna_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, author_id bigint, author_name varchar(100),
    title varchar(200) NOT NULL, content text NOT NULL, category varchar(50) NOT NULL,
    visibility varchar(20) NOT NULL, status varchar(20) NOT NULL, secret_pin varchar(20),
    created_at timestamp(6) with time zone NOT NULL, updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT qna_questions_category_check CHECK (category IN ('USAGE', 'PAYMENT', 'BICYCLE_FAULT', 'STATION', 'ACCOUNT', 'LOCATION', 'OTHER')),
    CONSTRAINT qna_questions_visibility_check CHECK (visibility IN ('PUBLIC', 'PRIVATE')),
    CONSTRAINT qna_questions_status_check CHECK (status IN ('PENDING', 'ANSWERED', 'CLOSED', 'HIDDEN'))
);
CREATE TABLE qna_answers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, question_id bigint NOT NULL,
    responder_id bigint, responder_name varchar(100), content text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL, updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT fk_qna_answers_question FOREIGN KEY (question_id) REFERENCES qna_questions(id)
);

CREATE TABLE favorite_stations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL,
    station_id bigint NOT NULL, station_name varchar(150), created_at timestamp with time zone NOT NULL,
    CONSTRAINT uk_favorite_user_station UNIQUE (user_id, station_id)
);
CREATE TABLE saved_routes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL,
    name varchar(100) NOT NULL, start_station_id bigint NOT NULL, start_station_name varchar(150),
    end_station_id bigint NOT NULL, end_station_name varchar(150), travel_mode varchar(50),
    created_at timestamp with time zone NOT NULL
);
CREATE TABLE prediction_histories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL,
    query_condition text NOT NULL, summary_result text NOT NULL, queried_at timestamp with time zone NOT NULL
);
CREATE INDEX ix_prediction_history_user_queried ON prediction_histories (user_id, queried_at DESC);
CREATE TABLE alert_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL,
    station_id bigint NOT NULL, condition_type varchar(50) NOT NULL, threshold integer,
    enabled boolean NOT NULL, created_at timestamp with time zone NOT NULL
);
CREATE TABLE in_app_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL,
    dedup_key varchar(150) NOT NULL, title varchar(200) NOT NULL, message text NOT NULL,
    created_at timestamp with time zone NOT NULL, read_at timestamp with time zone,
    CONSTRAINT uk_in_app_notification_user_dedup UNIQUE (user_id, dedup_key)
);
CREATE INDEX ix_notification_user_created ON in_app_notifications (user_id, created_at DESC);
