CREATE TABLE saved_prediction_routes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    kind varchar(20) NOT NULL,
    display_name varchar(300) NOT NULL,
    origin_name varchar(150) NOT NULL,
    origin_latitude numeric(10,7) NOT NULL,
    origin_longitude numeric(10,7) NOT NULL,
    destination_name varchar(150),
    destination_latitude numeric(10,7),
    destination_longitude numeric(10,7),
    station_id varchar(100),
    travel_mode varchar(50) NOT NULL,
    direct_minutes integer,
    required_bike_count integer NOT NULL,
    route_key varchar(128) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_saved_prediction_route_kind CHECK (kind IN ('ROUTE', 'DIRECT')),
    CONSTRAINT ck_saved_prediction_route_bikes CHECK (required_bike_count BETWEEN 1 AND 5),
    CONSTRAINT ck_saved_prediction_route_minutes CHECK (direct_minutes IS NULL OR direct_minutes BETWEEN 1 AND 240),
    CONSTRAINT uk_saved_prediction_route_user_key UNIQUE (user_id, route_key)
);
CREATE INDEX ix_saved_prediction_route_user_created ON saved_prediction_routes (user_id, created_at DESC);

ALTER TABLE prediction_histories ADD COLUMN IF NOT EXISTS station_id varchar(100);
ALTER TABLE prediction_histories ADD COLUMN IF NOT EXISTS station_name varchar(150);
ALTER TABLE prediction_histories ADD COLUMN IF NOT EXISTS availability_level varchar(20);
ALTER TABLE prediction_histories ADD COLUMN IF NOT EXISTS prediction_status varchar(20);
ALTER TABLE prediction_histories ADD COLUMN IF NOT EXISTS prediction_target_at timestamp with time zone;
ALTER TABLE prediction_histories ADD COLUMN IF NOT EXISTS required_bike_count integer;

CREATE UNIQUE INDEX IF NOT EXISTS uk_alert_rule_user_station_type_threshold
    ON alert_rules (user_id, station_id, condition_type, threshold);
CREATE INDEX IF NOT EXISTS ix_alert_rule_user_created ON alert_rules (user_id, created_at DESC);

ALTER TABLE in_app_notifications ADD COLUMN IF NOT EXISTS notification_type varchar(50) NOT NULL DEFAULT 'LEGACY';
CREATE INDEX IF NOT EXISTS ix_notification_user_unread_created ON in_app_notifications (user_id, read_at, created_at DESC);
