import { useCallback, useEffect, useState } from "react";
import { canDo, fixture } from "./adminFixture";
import { answerQuestion, hideQuestion, listAdminQuestions } from "./qnaAdminApi";
import { changeAdminUserRole, listAdminUsers } from "./adminUsersApi";
import { listAdminAuditLogs } from "./adminAuditLogsApi";
import { QnaAnswerDetail } from "./AdminDetailViews";
import { createAdminExport, downloadAdminExport, listAdminExports } from "./adminExportsApi";
import { activateAdminModel, approveAdminModel, listAdminModels, rollbackAdminModel, validateAdminModel } from "./adminModelOpsApi";
import { getAdminOverview } from "./adminOverviewApi";
import { getAdminPerformance } from "./adminPerformanceApi";
import { getAdminDataQuality } from "./adminDataQualityApi";
import { getAdminPredictionBatches } from "./adminPredictionBatchApi";

const Icon = ({ children }) => <span className="admin-card-icon" aria-hidden="true">{children}</span>;
const Button = ({ children, onClick, kind = "secondary", disabled = false }) => <button type="button" className={`admin-button ${kind}`} onClick={onClick} disabled={disabled}>{children}</button>;
const Chip = ({ children, tone = "blue" }) => <span className={`admin-chip ${tone}`}>{children}</span>;

function Section({ title, action, children, className = "" }) {
  return <section className={`admin-panel ${className}`}><header className="admin-panel-head"><h2>{title}</h2>{action}</header>{children}</section>;
}

function StatCard({ label, value, note, icon, tone = "blue" }) {
  return <article className={`admin-stat-card ${tone}`}><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div><Icon>{icon}</Icon></article>;
}

const formatDecimal = (value, digits) => value != null && Number.isFinite(Number(value)) ? Number(value).toFixed(digits) : "-";
const formatTimestamp = (value) => value && !Number.isNaN(new Date(value).getTime()) ? new Date(value).toLocaleString("ko-KR", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }) : "-";
const formatPercent = (value) => formatDecimal(value == null ? null : Number(value) * 100, 1);
const formatCount = (value) => value == null ? "-" : new Intl.NumberFormat("ko-KR").format(value);
const formatBatchTime = (value) => value && !Number.isNaN(new Date(value).getTime()) ? new Date(value).toLocaleString("ko-KR", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }) : "-";
const formatDuration = (seconds) => seconds == null ? "-" : seconds < 60 ? `${seconds}초` : `${Math.floor(seconds / 60)}분 ${seconds % 60}초`;

export function AdminStatePanel({ state }) {
  const content = {
    loading: ["불러오는 중", "관리자 데이터를 준비하고 있습니다."],
    unavailable: ["운영 현황 API 준비 중", "실제 운영 현황 API가 준비되면 이 화면에 표시합니다."],
    empty: ["표시할 항목이 없습니다", "필터를 조정하거나 다시 시도해 주세요."],
    error: ["일시적으로 표시할 수 없습니다", "잠시 후 다시 시도해 주세요."],
    forbidden: ["관리자 권한이 필요합니다", "관리자 데이터와 카드, 표는 표시하지 않습니다."],
    unauthorized: ["로그인이 필요합니다", "로그인 후 다시 시도해 주세요."],
  }[state] || ["알 수 없는 상태", ""];
  return <section className="admin-state-panel" data-testid={`admin-${state}`} aria-live="polite"><Icon>{state === "error" ? "!" : state === "forbidden" ? "×" : "…"}</Icon><h1>{content[0]}</h1><p>{content[1]}</p></section>;
}

function Dashboard() {
  const AdminAccuracyMap = require("./AdminAccuracyMap").default;
  const [overview, setOverview] = useState(null); const [performance, setPerformance] = useState(null); const [overviewState, setOverviewState] = useState("unavailable"); const [performanceState, setPerformanceState] = useState("loading");
  const load = useCallback(() => { setPerformanceState("loading"); getAdminOverview().then((data) => { setOverview(data); setOverviewState("success"); }).catch(() => setOverviewState("error")); getAdminPerformance().then((data) => { setPerformance(data); setPerformanceState("success"); }).catch((error) => setPerformanceState(error.status === 404 ? "empty" : "error")); }, []);
  useEffect(() => { load(); }, [load]);
  const weightedBrier = performance?.combinations?.length ? (performance.combinations.reduce((sum, row) => sum + row.sampleCount * row.brierScore, 0) / performance.combinations.reduce((sum, row) => sum + row.sampleCount, 0)).toFixed(4) : "-";
  const weakSegments = (performance?.segments || []).filter((row) => row.axis === "HOUR_BUCKET_X_STATION_SIZE").sort((a, b) => (b.brierScore ?? -1) - (a.brierScore ?? -1)).slice(0, 5);
  const renderCalibrationBin = (bin) => {
    const label = `${bin.binLowerPercent}-${bin.binUpperPercent}%`;
    if (bin.sampleCount === 0) return <div key={bin.binLowerPercent} className="admin-calibration-bin empty" aria-label={`${label} · 표본 없음`}><span>표본 없음</span></div>;
    return <div key={bin.binLowerPercent} className="admin-calibration-bin" aria-label={`${label} · 표본 ${bin.sampleCount} · 실제 비율 ${formatPercent(bin.actualRate)}% · 예측 확률 ${formatPercent(bin.meanPredicted)}%`}><span data-testid="calibration-actual" className="actual" style={{ height: `${Math.max(3, (bin.actualRate ?? 0) * 100)}%` }} /><span data-testid="calibration-predicted" className="predicted" style={{ height: `${Math.max(3, (bin.meanPredicted ?? 0) * 100)}%` }} /></div>;
  };
  return <><div className="admin-page-title"><div><p className="admin-eyebrow">UI-ADMIN-01 · 실측 평가</p><h1>운영 현황</h1></div></div>{overviewState === "unavailable" ? <AdminStatePanel state="unavailable" /> : overviewState === "loading" ? <AdminStatePanel state="loading" /> : <><div className="admin-stat-grid"><StatCard label="서비스 상태" value={overview ? overview.serviceStatus : "불러오지 못함"} note="실시간 집계" icon="●" tone="green" /><StatCard label="데이터 신선도" value={overview ? `${overview.dataFreshness.ageMinutes ?? "-"}분` : "불러오지 못함"} note={overview?.dataFreshness?.status || ""} icon="◷" /><StatCard label="활성 모델" value={overview?.activeModel?.state === "NONE" ? "미설정" : overview?.activeModel?.modelVersion || "불러오지 못함"} note="registry 상태" icon="◇" /><StatCard label="가중 Brier" value={performanceState === "success" ? weightedBrier : "-"} note="20개 조합 표본 가중" icon="≈" tone="orange" /></div><div className="admin-dashboard-top"><Section title="20조합 Brier 히트맵" className="admin-trend-panel">{performanceState === "success" ? <div className="admin-performance-heatmap">{performance.combinations.map((row) => <span key={`${row.horizonMinutes}-${row.requiredBikeCount}`} className={row.brierScore <= .035 ? "good" : row.brierScore <= .055 ? "warn" : "bad"}>{row.horizonMinutes}m · {row.requiredBikeCount}대<br />{formatDecimal(row.brierScore, 4)}</span>)}</div> : <p className="admin-performance-empty">{performanceState === "empty" ? "평가 결과가 아직 없습니다" : "평가 결과를 불러오지 못했습니다"}</p>}</Section><Section title="대기 항목" className="admin-pending-panel"><div className="admin-performance-pending"><p>Export <b>{overview?.pending?.exports ?? "-"}</b></p><p>모델 승인 <b>{overview?.pending?.modelApprovals ?? "-"}</b></p><p>미답변 Q&A <b>{overview?.pending?.qnaUnanswered ?? "-"}</b></p></div></Section></div><Section title="신뢰도 곡선 · 세그먼트 취약구간" className="admin-tall-panel"><p className="admin-performance-notice">평가 artifact ceeccc… · 현재 서비스 운영 모델과 다를 수 있습니다</p>{performanceState === "success" && <><div className="admin-calibration-legend" aria-label="신뢰도 곡선 범례"><span className="actual">실제 비율</span><span className="predicted">예측 확률</span></div><div className="admin-calibration" role="img" aria-label="실제 비율과 예측 확률 신뢰도 곡선">{performance.calibrationBins.map(renderCalibrationBin)}</div><table><thead><tr><th>구간</th><th>표본</th><th>Brier</th><th>Skill score</th></tr></thead><tbody>{weakSegments.map((row) => <tr key={row.segmentValue}><td>{row.segmentValue}</td><td>{row.sampleCount}</td><td>{row.status === "UNKNOWN_INSUFFICIENT_SAMPLES" ? "표본 부족" : formatDecimal(row.brierScore, 4)}</td><td>{row.status === "UNKNOWN_INSUFFICIENT_SAMPLES" ? "-" : formatDecimal(row.skillScore, 3)}</td></tr>)}</tbody></table></>}</Section>{performanceState === "success" && performance.segments.some((row) => row.axis === "STATION") && <AdminAccuracyMap segments={performance.segments} />}</>}<div className="admin-action-row"><Button onClick={load}>다시 시도</Button></div></>;
}

function Users() {
  const [items, setItems] = useState([]); const [query, setQuery] = useState(""); const [state, setState] = useState("loading");
  const [dialog, setDialog] = useState(null); const [nextRole, setNextRole] = useState("USER"); const [reason, setReason] = useState(""); const [actionError, setActionError] = useState("");
  const load = useCallback((nextQuery = "") => { setState("loading"); listAdminUsers({ q: nextQuery }).then((page) => { setItems(page.items); setState(page.items.length ? "success" : "empty"); }).catch((error) => setState(error.status === 401 ? "unauthorized" : error.status === 403 ? "forbidden" : "error")); }, []);
  useEffect(() => { load(); }, [load]);
  if (state !== "success") return <><AdminStatePanel state={state} /><div className="admin-action-row"><Button onClick={() => load()}>다시 시도</Button></div></>;
  const openDialog = (user) => { setDialog(user); setNextRole(user.role === "ADMIN" ? "USER" : "ADMIN"); setReason(""); setActionError(""); };
  const confirmRole = async () => { try { await changeAdminUserRole(dialog.userId, nextRole, reason); setDialog(null); load(); } catch (error) { setActionError(error.code === "LAST_SUPER_ADMIN_REQUIRED" ? "마지막 ADMIN의 역할은 낮출 수 없습니다." : error.status === 404 ? "사용자를 찾을 수 없습니다." : "역할 변경에 실패했습니다."); } };
  return <><div className="admin-page-title"><div><p className="admin-eyebrow">UI-ADMIN-02</p><h1>사용자 · 권한</h1><span>실제 API의 공개 UUID, 표시 이름, 역할만 표시합니다.</span></div></div>
    <form className="admin-filter-row" onSubmit={(event) => { event.preventDefault(); load(query); }}><input aria-label="사용자 검색" placeholder="표시 이름 검색" value={query} onChange={(event) => setQuery(event.target.value)} /><Button kind="primary" onClick={() => load(query)}>검색</Button><span>총 {items.length}명</span></form>
    <div className="admin-users-layout"><Section title="사용자 목록" className="admin-table-panel"><table><thead><tr><th>사용자</th><th>역할</th><th>작업</th></tr></thead><tbody>{items.map((user) => <tr key={user.userId}><td><strong>{user.displayName}</strong><small>{user.userId}</small></td><td><Chip>{user.role}</Chip></td><td><Button onClick={() => openDialog(user)}>역할 변경</Button></td></tr>)}</tbody></table></Section><aside className="admin-user-side"><Section title="안전한 표시 원칙"><div className="admin-safe-list"><p>✓ 이메일은 표시하지 않습니다.</p><p>✓ OAuth 식별자는 표시하지 않습니다.</p><p>✓ 내부 숫자 ID는 표시하지 않습니다.</p></div></Section></aside></div>
    {dialog && <Dialog title="역할 변경 확인" onClose={() => setDialog(null)}><p><b>{dialog.displayName}</b>의 역할을 변경합니다.</p><label>새 역할<select aria-label="새 역할" value={nextRole} onChange={(event) => setNextRole(event.target.value)}><option value="USER">USER</option><option value="ADMIN">ADMIN</option></select></label><label>변경 사유<textarea aria-label="변경 사유" value={reason} onChange={(event) => setReason(event.target.value)} /></label>{actionError && <p role="alert">{actionError}</p>}<div className="admin-dialog-actions"><Button onClick={() => setDialog(null)}>취소</Button><Button kind="primary" disabled={reason.trim().length < 2 || reason.trim().length > 200} onClick={confirmRole}>변경 확인</Button></div></Dialog>}</>;
}

function Export({ actorRole }) {
  const [items, setItems] = useState([]); const [state, setState] = useState("loading"); const [quality, setQuality] = useState(null); const [qualityState, setQualityState] = useState("loading"); const [source, setSource] = useState("CURATED"); const [format, setFormat] = useState("CSV"); const [purpose, setPurpose] = useState(""); const [rowCount, setRowCount] = useState("1000"); const [actionError, setActionError] = useState(""); const [downloading, setDownloading] = useState(null);
  const load = useCallback(() => { setState("loading"); setQualityState("loading"); listAdminExports().then((page) => { setItems(page.items); setState(page.items.length ? "success" : "empty"); }).catch((error) => setState(error.status === 401 ? "unauthorized" : error.status === 403 ? "forbidden" : "error")); getAdminDataQuality().then((data) => { setQuality(data); setQualityState("success"); }).catch(() => setQualityState("error")); }, []);
  useEffect(() => { load(); }, [load]);
  const requestExport = async () => { setActionError(""); try { await createAdminExport({ source, format, purpose: purpose.trim() || null, rowCount: Number(rowCount) }); load(); } catch (error) { setActionError(error.code === "VALIDATION_ERROR" ? "입력값 또는 행 수 상한을 확인해 주세요." : "Export 생성에 실패했습니다."); } };
  const download = async (item) => { setActionError(""); setDownloading(item.exportId); try { const blob = await downloadAdminExport(item.exportId); if (typeof URL.createObjectURL === "function") { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `export-${item.exportId}`; link.click(); URL.revokeObjectURL(url); } } catch (error) { setActionError(error.code === "EXPORT_EXPIRED" ? "다운로드 기간이 만료되었습니다." : "다운로드 파일을 찾을 수 없습니다."); } finally { setDownloading(null); } };
  if (state !== "success" && state !== "empty") return <><AdminStatePanel state={state} /><div className="admin-action-row"><Button onClick={load}>다시 시도</Button></div></>;
  return <><div className="admin-page-title"><div><p className="admin-eyebrow">UI-ADMIN-03</p><h1>데이터 · Export</h1><span>서버가 생성한 비식별 데이터만 내려받습니다.</span></div></div>
    <Section title="데이터 품질 · 신선도 SLO" className="admin-quality-panel">{qualityState === "success" ? <div className="admin-quality-content"><div className="admin-quality-summary"><p><span>수집 대여소</span><b>{quality.collection.latestStationCount} / {quality.collection.expectedStationCount}</b></p><p><span>누락 대여소 (활성 대여소 중 수집 행 없음)</span><b>{quality.collection.missingStationCount}</b></p><p><span>지연 P50 / P95</span><b>{quality.freshness.p50DelayMinutes ?? "-"}분 / {quality.freshness.p95DelayMinutes ?? "-"}분</b></p><p><span>신선도</span><b>{quality.freshness.status}</b></p></div><div className="admin-quality-breakdown"><span>현재 재고 상태</span>{Object.entries(quality.inventoryStatusBreakdown).map(([status, count]) => <p key={status}><b>{status === "MISSING" ? "MISSING (수집 행 상태)" : status}</b><span>{count}</span></p>)}</div><small>기준 시각 {formatTimestamp(quality.collection.latestCollectedAt)} · 생성 {formatTimestamp(quality.generatedAt)}</small></div> : <p className="admin-quality-empty">{qualityState === "loading" ? "데이터 품질을 불러오는 중입니다." : "데이터 품질을 불러오지 못했습니다."}</p>}</Section>
    <Section title="제한 Export 요청" className="admin-tall-panel"><div className="admin-filter-row"><select aria-label="Export 원본" value={source} onChange={(event) => setSource(event.target.value)}><option value="CURATED">CURATED</option><option value="QUARANTINE_NORMALIZED">QUARANTINE_NORMALIZED</option></select><select aria-label="Export 형식" value={format} onChange={(event) => setFormat(event.target.value)}><option value="CSV">CSV</option><option value="PARQUET">Parquet</option></select><input aria-label="Export 목적" value={purpose} onChange={(event) => setPurpose(event.target.value)} placeholder="사용 목적" /><input aria-label="Export 행 수" type="number" min="0" value={rowCount} onChange={(event) => setRowCount(event.target.value)} />{canDo(actorRole, "export_request") && <Button kind="primary" onClick={requestExport}>Export 요청</Button>}</div>{actionError && <p role="alert">{actionError}</p>}{state === "empty" ? <><AdminStatePanel state="empty" /><div className="admin-action-row"><Button onClick={load}>다시 시도</Button></div></> : <table><thead><tr><th>요청</th><th>원본</th><th>형식</th><th>상태</th><th>행 수</th><th>작업</th></tr></thead><tbody>{items.map((item) => <tr key={item.exportId}><td>{item.exportId}</td><td>{item.source}</td><td>{item.format}</td><td><Chip tone={item.status === "COMPLETED" ? "green" : "blue"}>{item.status}</Chip></td><td>{item.rowCount ?? "-"}</td><td>{item.status === "COMPLETED" && <Button onClick={() => download(item)} disabled={downloading === item.exportId}>{downloading === item.exportId ? "다운로드 준비 중" : "다운로드"}</Button>}</td></tr>)}</tbody></table>}</Section></>;
}

function Audit() {
  const [filters, setFilters] = useState({ action: "", result: "", reasonCode: "", from: "", to: "" });
  const [page, setPage] = useState(0); const [resultPage, setResultPage] = useState(null); const [state, setState] = useState("loading");
  const load = useCallback((nextPage, nextFilters) => { setState("loading"); listAdminAuditLogs({ ...nextFilters, page: nextPage }).then((response) => { setResultPage(response); setPage(nextPage); setState(response.items.length ? "success" : "empty"); }).catch((error) => setState(error.status === 401 ? "unauthorized" : error.status === 403 ? "forbidden" : "error")); }, []);
  useEffect(() => { load(0, { action: "", result: "", reasonCode: "", from: "", to: "" }); }, [load]);
  const updateFilter = (name, value) => setFilters((current) => ({ ...current, [name]: value }));
  const stateText = { loading: "감사 로그를 불러오는 중입니다.", empty: "조건에 맞는 감사 로그가 없습니다.", unauthorized: "로그인이 필요합니다.", forbidden: "관리자 권한이 필요합니다.", error: "감사 로그를 표시할 수 없습니다." };
  return <><div className="admin-page-title"><div><p className="admin-eyebrow">UI-ADMIN-04</p><h1>감사 로그</h1><span>실제 API의 비식별 감사 행만 표시합니다.</span></div></div><form className="admin-filter-row" onSubmit={(event) => { event.preventDefault(); load(0, filters); }}><input aria-label="행위 필터" placeholder="행위" value={filters.action} onChange={(event) => updateFilter("action", event.target.value)} /><select aria-label="결과 필터" value={filters.result} onChange={(event) => updateFilter("result", event.target.value)}><option value="">전체 결과</option><option value="SUCCESS">성공</option><option value="FAILURE">실패</option></select><input aria-label="사유 코드 필터" placeholder="사유 코드" value={filters.reasonCode} onChange={(event) => updateFilter("reasonCode", event.target.value)} /><input aria-label="시작 시각" type="datetime-local" value={filters.from} onChange={(event) => updateFilter("from", event.target.value)} /><input aria-label="종료 시각" type="datetime-local" value={filters.to} onChange={(event) => updateFilter("to", event.target.value)} /><Button kind="primary" onClick={() => load(0, filters)}>조회</Button></form>{state !== "success" ? <><section className="admin-state-panel" aria-live="polite"><h1>{stateText[state]}</h1></section><div className="admin-action-row"><Button onClick={() => load(page, filters)}>다시 시도</Button></div></> : <div className="admin-dashboard-grid"><Section title="정규화 감사 로그" className="admin-tall-panel"><table><thead><tr><th>시각</th><th>행위</th><th>사용자 역할</th><th>대상</th><th>결과</th></tr></thead><tbody>{resultPage.items.map((item) => <tr key={`${item.correlationId}-${item.occurredAt}`}><td>{item.occurredAt}</td><td><strong>{item.action}</strong></td><td>{item.actorRole}</td><td>{item.targetType} · {item.targetId}</td><td><Chip tone={item.result === "SUCCESS" ? "green" : "coral"}>{item.result}</Chip></td></tr>)}</tbody></table><div className="admin-action-row"><Button disabled={page === 0} onClick={() => load(page - 1, filters)}>이전</Button><span>{page + 1} 페이지</span><Button disabled={(page + 1) * resultPage.size >= resultPage.total} onClick={() => load(page + 1, filters)}>다음</Button></div></Section><Section title="안전한 표시 원칙"><div className="admin-safe-list"><p>✓ IP 원문을 표시하지 않습니다.</p><p>✓ 이메일·OAuth 값은 표시하지 않습니다.</p><p>✓ Q&A 본문을 표시하지 않습니다.</p><p>✓ 대상은 비식별 문자열입니다.</p></div></Section></div>}</>;
}

function ModelOps({ actorRole }) {
  const [models, setModels] = useState([]); const [state, setState] = useState("loading"); const [batchData, setBatchData] = useState(null); const [batchState, setBatchState] = useState("loading"); const [actionError, setActionError] = useState(""); const [busy, setBusy] = useState(null);
  const load = useCallback(() => { setState("loading"); setBatchState("loading"); listAdminModels().then((items) => { setModels(items); setState(items.length ? "success" : "empty"); }).catch((error) => setState(error.status === 401 ? "unauthorized" : error.status === 403 ? "forbidden" : "error")); getAdminPredictionBatches().then((data) => { setBatchData(data); setBatchState(data.batches.length ? "success" : "empty"); }).catch(() => setBatchState("error")); }, []);
  useEffect(() => { load(); }, [load]);
  const run = async (id, action) => { setBusy(`${action}-${id ?? "rollback"}`); setActionError(""); try { if (action === "validate") await validateAdminModel(id); if (action === "approve") await approveAdminModel(id); if (action === "activate") await activateAdminModel(id); if (action === "rollback") await rollbackAdminModel(); load(); } catch (error) { setActionError(error.code === "MODEL_PROMOTION_GATE_FAILED" ? "승인 및 활성화 조건을 충족하지 않습니다." : error.code === "ROLLBACK_TARGET_UNAVAILABLE" ? "복원할 이전 모델이 없습니다." : error.code === "COMPENSATION_FAILED" ? "자동 복원에 실패했습니다. 운영자에게 알리세요." : "ModelOps 작업에 실패했습니다."); } finally { setBusy(null); } };
  const active = models.find((model) => model.state === "ACTIVE"); const latestBatch = batchData?.batches?.[0];
  const modelContent = state !== "success" && state !== "empty" ? <><AdminStatePanel state={state} /><div className="admin-action-row"><Button onClick={load}>다시 시도</Button></div></> : <><div className="admin-stat-grid"><StatCard label="등록 모델" value={models.length} note="실제 API 결과" icon="◇" /><StatCard label="승인 모델" value={models.filter((model) => model.state === "APPROVED").length} note="활성화 가능 후보" icon="◷" tone="orange" /><StatCard label="현재 ACTIVE" value={active?.version || "없음"} note="실제 API 상태" icon="✓" tone="green" /></div><Section title="모델 목록" className="admin-tall-panel">{actionError && <p role="alert">{actionError}</p>}{state === "empty" ? <AdminStatePanel state="empty" /> : <table><thead><tr><th>버전</th><th>상태</th><th>등록 시각</th><th>작업</th></tr></thead><tbody>{models.map((model) => <tr key={model.id}><td><strong>{model.version}</strong></td><td><Chip tone={model.state === "ACTIVE" ? "green" : model.state === "APPROVED" ? "purple" : "blue"}>{model.state}</Chip></td><td>{model.createdAt}</td><td><div className="admin-action-row">{model.state === "DRAFT" && <Button disabled={busy !== null || !canDo(actorRole, "validate_model")} onClick={() => run(model.id, "validate")}>검증</Button>}{model.state === "VALIDATED" && <Button kind="primary" disabled={busy !== null || !canDo(actorRole, "approve_model")} onClick={() => run(model.id, "approve")}>승인</Button>}{model.state === "APPROVED" && <Button kind="primary" disabled={busy !== null || !canDo(actorRole, "activate_model")} onClick={() => run(model.id, "activate")}>활성화</Button>}</div></td></tr>)}</tbody></table>}<div className="admin-action-row"><Button disabled={busy !== null || !active || !canDo(actorRole, "rollback_model")} onClick={() => run(null, "rollback")}>이전 ACTIVE로 롤백</Button></div></Section></>;
  return <><div className="admin-page-title"><div><p className="admin-eyebrow">UI-ADMIN-05</p><h1>ModelOps</h1><span>실제 등록 모델의 상태 전이와 활성화·롤백을 처리합니다.</span></div></div>{modelContent}<Section title="예측 배치 발행" className="admin-prediction-batches">{batchState === "loading" && <p className="admin-prediction-empty">예측 배치 이력을 불러오는 중입니다.</p>}{batchState === "error" && <p className="admin-prediction-empty">예측 배치 이력을 표시할 수 없습니다.</p>}{batchState === "empty" && <p className="admin-prediction-empty">발행된 예측 배치가 없습니다.</p>}{batchState === "success" && <><p className="admin-prediction-summary">활성 배치 {formatCount(batchData.summary.activeBatchCount)}건 · 최근 발행 지연 {formatDuration(batchData.summary.latestPublishLagSeconds)} · 커버리지 {formatCount(latestBatch.stationCount)} / {formatCount(batchData.summary.expectedStationCount)} {latestBatch.coverageRatio == null ? "-" : `(${formatPercent(latestBatch.coverageRatio)}%)`}</p><table><thead><tr><th>상태</th><th>기준 시각</th><th>발행 지연</th><th>커버리지</th><th>만료</th></tr></thead><tbody>{batchData.batches.map((batch) => <tr key={batch.batchId} className={batch.publishStatus === "ACTIVE" && batch.expired ? "admin-prediction-expired-active" : ""}><td><Chip tone={batch.publishStatus === "ACTIVE" && !batch.expired ? "green" : "blue"}>{batch.publishStatus}{batch.publishStatus === "ACTIVE" && batch.expired ? " · 만료됨" : ""}</Chip></td><td>{formatBatchTime(batch.featureAsOf)}</td><td>{formatDuration(batch.publishLagSeconds)}</td><td>{batch.coverageRatio == null ? "-" : `${formatCount(batch.stationCount)} (${formatPercent(batch.coverageRatio)}%)`}</td><td>{formatBatchTime(batch.expiresAt)} {batch.expired ? "(지남)" : "(남음)"}</td></tr>)}</tbody></table></>}</Section></>;
}
function Qna({ actorRole }) {
  const [items, setItems] = useState([]); const [selectedId, setSelectedId] = useState(null); const [state, setState] = useState("loading"); const [answer, setAnswer] = useState("");
  const load = () => { setState("loading"); listAdminQuestions().then((page) => { setItems(page.items); setSelectedId((id) => id || page.items[0]?.id); setState(page.items.length ? "success" : "empty"); }).catch(() => setState("error")); };
  const [detailId, setDetailId] = useState(null); useEffect(load, []); const selected = items.find((item) => item.id === selectedId); const detail = items.find((item) => item.id === detailId);
  if (state !== "success") return <AdminStatePanel state={state} />;
  const submitAnswer = async () => { if (!answer.trim()) return; try { await answerQuestion(selected.id, answer); setAnswer(""); load(); } catch { setState("error"); } };
  if (detail) return <QnaAnswerDetail question={detail} answer={answer} onAnswerChange={setAnswer} onAnswer={submitAnswer} onHide={() => hideQuestion(detail.id).then(() => { setDetailId(null); load(); }).catch(() => setState("error"))} onBack={() => setDetailId(null)} />;
  return <><div className="admin-page-title"><div><p className="admin-eyebrow">UI-ADMIN-06</p><h1>Q&A 관리</h1><span>실제 Q&A API를 통해 처리합니다.</span></div></div><div className="admin-dashboard-grid admin-qna-grid"><Section title={`문의 목록 · ${items.length}건`} className="admin-tall-panel admin-qna-list"><table><thead><tr><th>분류</th><th>질문 제목</th><th>공개 범위</th><th>상태</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className={item.id === selected?.id ? "is-selected" : ""}><td>{item.category}</td><td><button type="button" className="admin-table-link" onClick={() => { setSelectedId(item.id); setDetailId(item.id); }}>{item.title}</button></td><td><Chip tone={item.visibility === "PRIVATE" ? "purple" : "green"}>{item.visibility}</Chip></td><td><Chip>{item.status === "PENDING" ? "OPEN" : item.status}</Chip></td></tr>)}</tbody></table></Section>{selected && <aside className="admin-qna-side"><Section title="문의 처리"><div className="admin-qna-detail"><Chip>{selected.visibility}</Chip><h3>{selected.title}</h3><p>{selected.body}</p><textarea aria-label="답변 내용" value={answer} onChange={(event) => setAnswer(event.target.value)} /><div className="admin-action-row">{!selected.answers?.length && <Button kind="primary" onClick={submitAnswer}>답변 보내기</Button>}<Button onClick={() => hideQuestion(selected.id).then(load).catch(() => setState("error"))}>숨김</Button></div></div></Section></aside>}</div></>;
}

function Dialog({ title, children, onClose }) { return <div className="admin-dialog-backdrop" role="presentation"><section className="admin-dialog" role="dialog" aria-modal="true" aria-label={title}><button type="button" className="admin-dialog-close" aria-label="닫기" onClick={onClose}>×</button><h2>{title}</h2>{children}</section></div>; }

export function AdminPage({ menuId, actorRole, fixtureData = fixture, onAction = () => {} }) {
  const pages = { dashboard: <Dashboard />, users: <Users />, export: <Export actorRole={actorRole} />, audit: <Audit />, modelops: <ModelOps actorRole={actorRole} />, qna: <Qna data={fixtureData} actorRole={actorRole} onAction={onAction} /> };
  return <div className="admin-page">{pages[menuId] || pages.dashboard}</div>;
}
