import { useEffect, useMemo, useRef, useState } from 'react';
import AsyncStatePanel from '../../components/AsyncStatePanel';
import { availableActions } from './modelReleasesAdapter';

const ACTION_LABELS = { VALIDATE: '검증', APPROVE: '승인', REJECT: '반려', ACTIVATE: '활성화', ROLLBACK: '복원' };
const CONFIRM_ACTIONS = new Set(['ACTIVATE', 'ROLLBACK', 'REJECT']);
function isAccessError(error) { return error?.status === 401 || error?.status === 403; }
function formatTime(value) { return value ? new Date(value).toLocaleString('ko-KR') : '확인 정보 없음'; }
function SourceState({ source, permission, limitedLabel }) { if (source?.state === 'ACCESS_LIMITED') return <p className="model-releases-limited">{limitedLabel} <small>필요 권한: {permission}</small></p>; if (source?.state === 'FORBIDDEN') return <AsyncStatePanel state="FORBIDDEN" code={source.error?.code} requiredPermission={permission} />; if (source?.state === 'ERROR') return <AsyncStatePanel state="ERROR" code={source.error?.code} />; if (source?.state === 'UNAVAILABLE') return <p className="model-releases-limited">변경 이력 확인 불가 <small>{source.code}</small></p>; return null; }
function Runtime({ source }) { if (source?.state !== 'SUCCESS') return <SourceState source={source} permission="MODEL_METRICS_READ" limitedLabel="runtime identity 접근 제한" />; const runtime = source.data; return <dl className="model-releases-runtime-data"><div><dt>Serving model</dt><dd>{runtime.modelVersion}</dd></div><div><dt>Artifact SHA</dt><dd>{runtime.artifactSha256.slice(0, 12)}</dd></div><div><dt>Source</dt><dd>{runtime.modelSource}</dd></div><div><dt>지원 범위</dt><dd>H{runtime.supportedHorizons.join(', H')} · 수량 {runtime.supportedQuantities.join(', ')}</dd></div><div><dt>Loaded</dt><dd>{formatTime(runtime.loadedAt)}</dd></div></dl>; }
function RegistrySummary({ models }) { const counts = models.reduce((total, model) => ({ ...total, [model.state]: (total[model.state] || 0) + 1 }), {}); return <div className="model-releases-summary" aria-label="레지스트리 lifecycle 요약"><strong>총 {models.length}개</strong>{Object.entries(counts).map(([state, count]) => <span key={state}>{state} {count}</span>)}</div>; }
function RegistryTable({ models, permissions, actionPending, onAction }) { if (!models.length) return <p className="model-releases-limited">등록된 ModelOps lifecycle 항목 없음</p>; return <div className="model-releases-table-wrap"><table><caption>모델 레지스트리</caption><thead><tr><th scope="col">ID</th><th scope="col">버전</th><th scope="col">lifecycle</th><th scope="col">등록 시각</th><th scope="col">작업</th></tr></thead><tbody>{models.map((model) => { const actions = availableActions(model, permissions).filter((action) => action !== 'REGISTER' && action !== 'ROLLBACK'); return <tr key={model.id ?? model.version}><td>{model.id}</td><td>{model.version}</td><td><span className="model-releases-state">{model.state}</span></td><td>{formatTime(model.createdAt)}</td><td className="model-releases-actions">{actions.length ? actions.map((action) => <button key={action} type="button" aria-label={`${model.version} ${ACTION_LABELS[action]}`} disabled={Boolean(actionPending)} onClick={() => onAction(action, model.id)}>{actionPending === `${action}:${model.id}` ? '처리 중' : ACTION_LABELS[action]}</button>) : <span>-</span>}</td></tr>; })}</tbody></table></div>; }
function History({ source }) { const items = source?.data || []; if (!items.length) return <AsyncStatePanel state="EMPTY" />; return <div className="model-releases-table-wrap"><table><caption>모델 lifecycle 변경 이력</caption><thead><tr><th scope="col">시각</th><th scope="col">작업</th><th scope="col">결과</th><th scope="col">사유 코드</th></tr></thead><tbody>{items.map((item, index) => <tr key={`${item.occurredAt}-${item.action}-${index}`}><td>{formatTime(item.occurredAt)}</td><td>{item.action}</td><td>{item.result}</td><td>{item.reasonCode || '-'}</td></tr>)}</tbody></table></div>; }

export default function ModelReleasesPage({ createAdapter }) {
  const adapter = useMemo(() => createAdapter(), [createAdapter]); const [result, setResult] = useState(null); const [error, setError] = useState(null); const [loading, setLoading] = useState(true); const [actionPending, setActionPending] = useState(null); const [actionError, setActionError] = useState(null); const generation = useRef(0);
  useEffect(() => { const controller = new AbortController(); const current = ++generation.current; setLoading(true); setError(null); setResult(null); adapter.load({ signal: controller.signal }).then((next) => { if (!controller.signal.aborted && generation.current === current) setResult(next); }).catch((nextError) => { if (!controller.signal.aborted && nextError?.name !== 'AbortError' && generation.current === current) setError(nextError); }).finally(() => { if (!controller.signal.aborted && generation.current === current) setLoading(false); }); return () => controller.abort(); }, [adapter]);
  const runAction = async (type, id) => { if (actionPending) return; if (CONFIRM_ACTIONS.has(type) && !window.confirm(`${ACTION_LABELS[type]} 작업을 요청할까요?`)) return; const key = `${type}:${id ?? 'current'}`; setActionPending(key); setActionError(null); try { await adapter.action({ type, id }); if (adapter.refresh) { const refreshed = await adapter.refresh({ permissions: result?.permissions || [] }); setResult((previous) => ({ ...previous, ...refreshed })); } } catch (nextError) { setActionError(nextError); } finally { setActionPending(null); } };
  if (loading) return <main className="model-releases-page"><p className="model-releases-eyebrow">UI-MODEL-04</p><AsyncStatePanel state="LOADING" /></main>;
  if (error) return <AsyncStatePanel state={isAccessError(error) ? 'FORBIDDEN' : 'ERROR'} code={error.code} requiredPermission={isAccessError(error) ? 'MODEL_RELEASE_READ' : undefined} />;
  const models = result?.registry?.data || []; const permissions = result?.permissions || [];
  return <main className="model-releases-page" aria-label="모델 버전 관리"><header className="model-releases-header"><div><p className="model-releases-eyebrow">UI-MODEL-04</p><h1>모델 버전 관리</h1><p>runtime identity와 registry lifecycle을 독립된 source로 표시합니다.</p></div></header><section className="model-releases-runtime" aria-label="런타임 identity"><strong>LIVE_SERVING_EFFECT_UNVERIFIED</strong><p>활성화·복원 성공은 registry/action 요청 결과이며, 아래 runtime readback으로만 현재 serving identity를 확인합니다.</p><Runtime source={result?.runtime} /></section><section className="model-releases-section" aria-labelledby="registry-heading"><div className="model-releases-heading"><div><h2 id="registry-heading">모델 레지스트리</h2><p>ACTIVE는 레지스트리 lifecycle 상태입니다. 현재 serving 모델을 뜻하지 않습니다.</p></div></div>{result?.registry?.state === 'SUCCESS' ? <><RegistrySummary models={models} /><RegistryTable models={models} permissions={permissions} actionPending={actionPending} onAction={runAction} /></> : <SourceState source={result?.registry} permission="MODEL_METRICS_READ" limitedLabel="레지스트리 접근 제한" />}</section>{permissions.includes('MODEL_ARTIFACT_REGISTER') ? <p className="model-releases-limited">등록·업로드 입력 계약 없음 <small>민감 artifact reference 입력은 안전한 표시 범위에 승인되지 않았습니다.</small></p> : null}{permissions.includes('MODEL_ROLLBACK') ? <section className="model-releases-rollback"><div><strong>복원</strong><p>source-defined rollback target만 사용합니다.</p></div><button type="button" disabled={Boolean(actionPending)} onClick={() => runAction('ROLLBACK')}>{actionPending === 'ROLLBACK:current' ? '처리 중' : '복원 요청'}</button></section> : null}{actionError ? <p role="alert" className="model-releases-action-error">작업 요청 실패: {actionError.code || 'MODEL_ACTION_FAILED'}</p> : null}<section className="model-releases-section" aria-labelledby="history-heading"><div className="model-releases-heading"><div><h2 id="history-heading">변경 이력</h2><p>안전하게 범위를 한정한 MODEL lifecycle 이력 소스는 아직 없습니다.</p></div></div>{result?.history?.state === 'SUCCESS' ? <History source={result.history} /> : <SourceState source={result?.history} permission="AUDIT_READ" limitedLabel="변경 이력 접근 제한" />}</section></main>;
}
