import { useEffect, useMemo, useRef, useState } from 'react';
import AsyncStatePanel from '../../components/AsyncStatePanel';
import { availableActions } from './modelReleasesAdapter';

const ACTION_LABELS = { VALIDATE: '검증', APPROVE: '승인', REJECT: '반려', ACTIVATE: '활성화', ROLLBACK: '복원', RECONCILE: '현재 serving 동기화' };
const CONFIRM_ACTIONS = new Set(['ACTIVATE', 'ROLLBACK', 'REJECT']);
const EMPTY_METADATA = { version: '', codeCommit: '', dataManifestHash: '', configHash: '', featureSchemaVersion: '' };
function isAccessError(error) { return error?.status === 401 || error?.status === 403; }
function formatTime(value) { return value ? new Date(value).toLocaleString('ko-KR') : '확인 정보 없음'; }
function SourceState({ source, permission, limitedLabel }) { if (source?.state === 'ACCESS_LIMITED') return <p className="model-releases-limited">{limitedLabel} <small>필요 권한: {permission}</small></p>; if (source?.state === 'FORBIDDEN') return <AsyncStatePanel state="FORBIDDEN" code={source.error?.code} requiredPermission={permission} />; if (source?.state === 'ERROR') return <AsyncStatePanel state="ERROR" code={source.error?.code} />; if (source?.state === 'UNAVAILABLE') return <p className="model-releases-limited">변경 이력 확인 불가 <small>{source.code}</small></p>; return null; }
function Runtime({ source }) { if (source?.state !== 'SUCCESS') return <SourceState source={source} permission="MODEL_METRICS_READ" limitedLabel="runtime identity 접근 제한" />; const runtime = source.data; return <dl className="model-releases-runtime-data"><div><dt>Serving model</dt><dd>{runtime.modelVersion}</dd></div><div><dt>Artifact SHA</dt><dd>{runtime.artifactSha256.slice(0, 12)}</dd></div><div><dt>Source</dt><dd>{runtime.modelSource}</dd></div><div><dt>지원 범위</dt><dd>H{runtime.supportedHorizons.join(', H')} · 수량 {runtime.supportedQuantities.join(', ')}</dd></div><div><dt>Loaded</dt><dd>{formatTime(runtime.loadedAt)}</dd></div></dl>; }
function RegistrySummary({ models }) { const counts = models.reduce((total, model) => ({ ...total, [model.state]: (total[model.state] || 0) + 1 }), {}); return <div className="model-releases-summary" aria-label="레지스트리 lifecycle 요약"><strong>총 {models.length}개</strong>{Object.entries(counts).map(([state, count]) => <span key={state}>{state} {count}</span>)}</div>; }
function RegistryTable({ models, permissions, actionPending, onAction }) { if (!models.length) return <p className="model-releases-limited">등록된 ModelOps lifecycle 항목 없음</p>; return <div className="model-releases-table-wrap"><table><caption>모델 레지스트리</caption><thead><tr><th scope="col">ID</th><th scope="col">버전</th><th scope="col">artifact</th><th scope="col">schema</th><th scope="col">lifecycle</th><th scope="col">등록 시각</th><th scope="col">작업</th></tr></thead><tbody>{models.map((model) => { const actions = availableActions(model, permissions).filter((action) => action !== 'REGISTER' && action !== 'ROLLBACK'); return <tr key={model.id}><td>{model.id}</td><td>{model.version}<small>{model.codeCommit || '확인 정보 없음'}</small></td><td title={model.artifactSha256}>{model.artifactSha256 ? model.artifactSha256.slice(0, 12) : '확인 정보 없음'}</td><td>{model.featureSchemaVersion || '확인 정보 없음'}</td><td><span className="model-releases-state">{model.state}</span></td><td>{formatTime(model.createdAt)}</td><td className="model-releases-actions">{actions.length ? actions.map((action) => <button key={action} type="button" aria-label={`${model.version} ${ACTION_LABELS[action]}`} disabled={Boolean(actionPending)} onClick={() => onAction(action, model.id)}>{actionPending === `${action}:${model.id}` ? '처리 중' : ACTION_LABELS[action]}</button>) : <span>-</span>}</td></tr>; })}</tbody></table></div>; }
function History({ source }) { const items = source?.data || []; if (!items.length) return <AsyncStatePanel state="EMPTY" />; return <div className="model-releases-table-wrap"><table><caption>모델 lifecycle 변경 이력</caption><thead><tr><th scope="col">시각</th><th scope="col">작업</th><th scope="col">대상</th><th scope="col">버전</th><th scope="col">결과</th><th scope="col">사유 코드</th></tr></thead><tbody>{items.map((item, index) => <tr key={`${item.occurredAt}-${item.action}-${index}`}><td>{formatTime(item.occurredAt)}</td><td>{item.action}</td><td>{item.resourceType}</td><td>{item.resourceVersion}</td><td>{item.result}</td><td>{item.reasonCode || '-'}</td></tr>)}</tbody></table></div>; }

function RegistrationForm({ disabled, onRegister }) {
  const [metadata, setMetadata] = useState(EMPTY_METADATA); const [artifactFile, setArtifactFile] = useState(null); const [manifestFile, setManifestFile] = useState(null); const [evaluationsFile, setEvaluationsFile] = useState(null);
  const update = (name, value) => setMetadata((current) => ({ ...current, [name]: value }));
  const valid = Object.values(metadata).every((value) => value.trim()) && artifactFile?.size > 0 && manifestFile?.size > 0 && evaluationsFile?.size > 0;
  const submit = (event) => { event.preventDefault(); if (valid && !disabled) onRegister({ metadata, artifactFile, manifestFile, evaluationsFile }); };
  return <form className="model-releases-register" onSubmit={submit} aria-label="모델 업로드 및 등록"><div className="model-releases-heading"><div><h2>모델 업로드 · 등록</h2><p>브라우저에서 SHA-256을 계산한 뒤 artifact와 manifest를 순서대로 전송하고 20조합 평가를 함께 등록합니다.</p></div></div><div className="model-releases-form-grid"><label>모델 버전<input value={metadata.version} onChange={(event) => update('version', event.target.value)} required /></label><label>코드 commit<input value={metadata.codeCommit} onChange={(event) => update('codeCommit', event.target.value)} required /></label><label>데이터 manifest hash<input value={metadata.dataManifestHash} onChange={(event) => update('dataManifestHash', event.target.value)} required /></label><label>설정 hash<input value={metadata.configHash} onChange={(event) => update('configHash', event.target.value)} required /></label><label>Feature schema<input value={metadata.featureSchemaVersion} onChange={(event) => update('featureSchemaVersion', event.target.value)} required /></label><label>모델 artifact<input type="file" onChange={(event) => setArtifactFile(event.target.files?.[0] || null)} required /></label><label>Manifest<input type="file" onChange={(event) => setManifestFile(event.target.files?.[0] || null)} required /></label><label>20조합 평가<input type="file" accept="application/json,.json" onChange={(event) => setEvaluationsFile(event.target.files?.[0] || null)} required /></label></div><button type="submit" disabled={!valid || disabled}>{disabled ? '업로드 중' : '업로드 및 등록'}</button><p className="model-releases-form-note">파일명만 서버에 전달하며 내부 object key는 화면에 표시하지 않습니다.</p></form>;
}

export default function ModelReleasesPage({ createAdapter }) {
  const adapter = useMemo(() => createAdapter(), [createAdapter]); const [result, setResult] = useState(null); const [error, setError] = useState(null); const [loading, setLoading] = useState(true); const [actionPending, setActionPending] = useState(null); const [actionError, setActionError] = useState(null); const [servingVerification, setServingVerification] = useState(null); const generation = useRef(0);
  useEffect(() => { const controller = new AbortController(); const current = ++generation.current; setLoading(true); setError(null); setResult(null); adapter.load({ signal: controller.signal }).then((next) => { if (!controller.signal.aborted && generation.current === current) setResult(next); }).catch((nextError) => { if (!controller.signal.aborted && nextError?.name !== 'AbortError' && generation.current === current) setError(nextError); }).finally(() => { if (!controller.signal.aborted && generation.current === current) setLoading(false); }); return () => controller.abort(); }, [adapter]);
  const refresh = async () => { const refreshed = await adapter.refresh({ permissions: result?.permissions || [] }); setResult((previous) => ({ ...previous, ...refreshed })); return refreshed; };
  const runAction = async (type, id) => { if (actionPending) return; if (CONFIRM_ACTIONS.has(type) && !window.confirm(`${ACTION_LABELS[type]} 작업을 요청할까요?`)) return; const key = `${type}:${id ?? 'current'}`; setActionPending(key); setActionError(null); setServingVerification(null); try { const response = await adapter.action({ type, id }); if ((type === 'ACTIVATE' || type === 'ROLLBACK') && adapter.verifyServing) { const verification = typeof response?.candidateModelId === 'number' ? await adapter.verifyServing({ candidateModelId: response.candidateModelId, permissions: result?.permissions || [] }) : { state: 'UNAVAILABLE' }; if (verification.refreshed) setResult((previous) => ({ ...previous, ...verification.refreshed })); setServingVerification(verification); } else if (adapter.refresh) await refresh(); } catch (nextError) { setActionError(nextError); } finally { setActionPending(null); } };
  const register = async (values) => { if (actionPending) return; setActionPending('REGISTER:current'); setActionError(null); try { await adapter.register(values); await refresh(); } catch (nextError) { setActionError(nextError); } finally { setActionPending(null); } };
  if (loading) return <main className="model-releases-page"><p className="model-releases-eyebrow">UI-MODEL-04</p><AsyncStatePanel state="LOADING" /></main>;
  if (error) return <AsyncStatePanel state={isAccessError(error) ? 'FORBIDDEN' : 'ERROR'} code={error.code} requiredPermission={isAccessError(error) ? 'MODEL_RELEASE_READ' : undefined} />;
  const models = result?.registry?.data || []; const permissions = result?.permissions || []; const verificationLabel = servingVerification?.state || 'LIVE_SERVING_EFFECT_UNVERIFIED';
  return <main className="model-releases-page" aria-label="모델 버전 관리"><header className="model-releases-header"><div><p className="model-releases-eyebrow">UI-MODEL-04</p><h1>모델 버전 관리</h1><p>runtime identity와 registry lifecycle을 독립된 source로 표시합니다.</p></div></header><section className={`model-releases-runtime model-releases-runtime--${verificationLabel.toLowerCase()}`} aria-label="런타임 identity"><div><strong>{verificationLabel}</strong><p>{verificationLabel === 'VERIFIED' ? '요청 대상의 version과 artifact SHA가 실제 serving runtime과 일치합니다.' : '활성화·복원 결과는 runtime readback으로 확인하며, 확인 전에는 serving 효과를 보장하지 않습니다.'}</p></div><Runtime source={result?.runtime} /></section><section className="model-releases-section" aria-labelledby="registry-heading"><div className="model-releases-heading"><div><h2 id="registry-heading">모델 레지스트리</h2><p>ACTIVE는 레지스트리 lifecycle 상태입니다. 현재 serving 모델을 뜻하지 않습니다.</p></div>{!models.some((model) => model.state === 'ACTIVE') && permissions.includes('MODEL_ACTIVATE') ? <button type="button" disabled={Boolean(actionPending)} onClick={() => runAction('RECONCILE')}>{actionPending === 'RECONCILE:current' ? '동기화 중' : '현재 serving 동기화'}</button> : null}</div>{result?.registry?.state === 'SUCCESS' ? <><RegistrySummary models={models} /><RegistryTable models={models} permissions={permissions} actionPending={actionPending} onAction={runAction} /></> : <SourceState source={result?.registry} permission="MODEL_METRICS_READ" limitedLabel="레지스트리 접근 제한" />}</section>{permissions.includes('MODEL_ARTIFACT_REGISTER') ? <RegistrationForm disabled={actionPending === 'REGISTER:current'} onRegister={register} /> : null}{permissions.includes('MODEL_ROLLBACK') ? <section className="model-releases-rollback"><div><strong>복원</strong><p>source-defined rollback target만 사용합니다.</p></div><button type="button" disabled={Boolean(actionPending)} onClick={() => runAction('ROLLBACK')}>{actionPending === 'ROLLBACK:current' ? '처리 중' : '복원 요청'}</button></section> : null}{actionError ? <p role="alert" className="model-releases-action-error">작업 요청 실패: {actionError.code || 'MODEL_ACTION_FAILED'}</p> : null}<section className="model-releases-section" aria-labelledby="history-heading"><div className="model-releases-heading"><div><h2 id="history-heading">변경 이력</h2><p>MODEL 범위의 안전한 lifecycle 이력만 표시합니다.</p></div></div>{result?.history?.state === 'SUCCESS' ? <History source={result.history} /> : <SourceState source={result?.history} permission="MODEL_RELEASE_READ" limitedLabel="변경 이력 접근 제한" />}</section></main>;
}
