import { useEffect, useMemo, useRef, useState } from 'react';
import AsyncStatePanel from '../../components/AsyncStatePanel';
import { availableActions } from './modelReleasesAdapter';

const ACTION_LABELS = { VALIDATE: '검증', APPROVE: '승인', REJECT: '반려', ACTIVATE: '활성화', ROLLBACK: '복원' };
const CONFIRM_ACTIONS = new Set(['ACTIVATE', 'ROLLBACK', 'REJECT']);
function isAccessError(error) { return error?.status === 401 || error?.status === 403; }
function formatTime(value) { return value ? new Date(value).toLocaleString('ko-KR') : '확인 정보 없음'; }
function statePanel(source, permission) {
  if (source?.state === 'ACCESS_LIMITED') return <p className="model-releases-limited">{permission === 'MODEL_METRICS_READ' ? '레지스트리 접근 제한' : '변경 이력 접근 제한'} <small>필요 권한: {permission}</small></p>;
  if (source?.state === 'FORBIDDEN') return <AsyncStatePanel state="FORBIDDEN" code={source.error?.code} requiredPermission={permission} />;
  if (source?.state === 'ERROR') return <AsyncStatePanel state="ERROR" code={source.error?.code} />;
  if (source?.state === 'UNAVAILABLE') return <p className="model-releases-limited">변경 이력 확인 불가 <small>{source.code}</small></p>;
  return null;
}
function RegistrySummary({ models }) { const counts = models.reduce((total, model) => ({ ...total, [model.state]: (total[model.state] || 0) + 1 }), {}); return <div className="model-releases-summary" aria-label="레지스트리 lifecycle 요약"><strong>총 {models.length}개</strong>{Object.entries(counts).map(([state, count]) => <span key={state}>{state} {count}</span>)}</div>; }
function RegistryTable({ models, permissions, actionPending, onAction }) {
  if (!models.length) return <AsyncStatePanel state="EMPTY" />;
  return <div className="model-releases-table-wrap"><table><caption>모델 레지스트리</caption><thead><tr><th scope="col">ID</th><th scope="col">버전</th><th scope="col">lifecycle</th><th scope="col">등록 시각</th><th scope="col">작업</th></tr></thead><tbody>{models.map((model) => {
    const actions = availableActions(model, permissions).filter((action) => action !== 'REGISTER' && action !== 'ROLLBACK');
    return <tr key={model.id ?? model.version}><td>{model.id}</td><td>{model.version}</td><td><span className="model-releases-state">{model.state}</span></td><td>{formatTime(model.createdAt)}</td><td className="model-releases-actions">{actions.length ? actions.map((action) => <button key={action} type="button" disabled={Boolean(actionPending)} onClick={() => onAction(action, model.id)}>{actionPending === `${action}:${model.id}` ? '처리 중' : ACTION_LABELS[action]}</button>) : <span>-</span>}</td></tr>;
  })}</tbody></table></div>;
}
function History({ source }) { const items = source?.data || []; if (!items.length) return <AsyncStatePanel state="EMPTY" />; return <div className="model-releases-table-wrap"><table><caption>모델 lifecycle 변경 이력</caption><thead><tr><th scope="col">시각</th><th scope="col">작업</th><th scope="col">결과</th><th scope="col">사유 코드</th></tr></thead><tbody>{items.map((item, index) => <tr key={`${item.occurredAt}-${item.action}-${index}`}><td>{formatTime(item.occurredAt)}</td><td>{item.action}</td><td>{item.result}</td><td>{item.reasonCode || '-'}</td></tr>)}</tbody></table></div>; }
function Batches({ source }) { const data = source?.data; const batches = Array.isArray(data?.batches) ? data.batches : []; if (source?.state !== 'SUCCESS') return statePanel(source, 'MODEL_RELEASE_READ'); if (!batches.length) return <AsyncStatePanel state="EMPTY" />; return <div className="model-releases-table-wrap"><table><caption>예측 배치</caption><thead><tr><th scope="col">상태</th><th scope="col">모델 버전</th><th scope="col">기준 시각</th><th scope="col">커버리지</th><th scope="col">만료</th></tr></thead><tbody>{batches.map((batch) => <tr key={batch.batchId ?? batch.featureAsOf}><td>{batch.publishStatus || '-'}</td><td>{batch.modelVersion || '-'}</td><td>{formatTime(batch.featureAsOf)}</td><td>{batch.coverageRatio == null ? '-' : `${Math.round(batch.coverageRatio * 100)}%`}</td><td>{formatTime(batch.expiresAt)}</td></tr>)}</tbody></table></div>; }

export default function ModelReleasesPage({ createAdapter }) {
  const adapter = useMemo(() => createAdapter(), [createAdapter]); const [result, setResult] = useState(null); const [error, setError] = useState(null); const [loading, setLoading] = useState(true); const [actionPending, setActionPending] = useState(null); const [actionError, setActionError] = useState(null); const generation = useRef(0);
  useEffect(() => { const controller = new AbortController(); const current = ++generation.current; setLoading(true); setError(null); setResult(null); adapter.load({ signal: controller.signal }).then((next) => { if (!controller.signal.aborted && generation.current === current) setResult(next); }).catch((nextError) => { if (!controller.signal.aborted && nextError?.name !== 'AbortError' && generation.current === current) setError(nextError); }).finally(() => { if (!controller.signal.aborted && generation.current === current) setLoading(false); }); return () => controller.abort(); }, [adapter]);
  const runAction = async (type, id) => { if (actionPending) return; if (CONFIRM_ACTIONS.has(type) && !window.confirm(`${ACTION_LABELS[type]} 작업을 요청할까요?`)) return; const key = `${type}:${id ?? 'current'}`; setActionPending(key); setActionError(null); try { await adapter.action({ type, id }); if (adapter.refresh) { const refreshed = await adapter.refresh({ permissions: result?.permissions || [] }); setResult((previous) => ({ ...previous, ...refreshed })); } } catch (nextError) { setActionError(nextError); } finally { setActionPending(null); } };
  if (loading) return <main className="model-releases-page"><p className="model-releases-eyebrow">UI-MODEL-04</p><AsyncStatePanel state="LOADING" /></main>;
  if (error) return <AsyncStatePanel state={isAccessError(error) ? 'FORBIDDEN' : 'ERROR'} code={error.code} requiredPermission={isAccessError(error) ? 'MODEL_RELEASE_READ' : undefined} />;
  const models = result?.registry?.data || []; const permissions = result?.permissions || [];
  return <main className="model-releases-page" aria-label="모델 버전 관리"><header className="model-releases-header"><div><p className="model-releases-eyebrow">UI-MODEL-04</p><h1>모델 버전 관리</h1><p>레지스트리 lifecycle과 예측 배치를 서로 독립된 권한·소스로 표시합니다.</p></div></header><section className="model-releases-runtime" aria-label="런타임 확인 제한"><strong>LIVE_SERVING_EFFECT_UNVERIFIED</strong><p>활성화·복원 성공은 registry/action 요청 결과일 뿐, inference runtime이 현재 제공하는 모델 identity의 증거가 아닙니다.</p></section><section className="model-releases-section" aria-labelledby="registry-heading"><div className="model-releases-heading"><div><h2 id="registry-heading">모델 레지스트리</h2><p>ACTIVE는 레지스트리 lifecycle 상태입니다. 현재 serving 모델을 뜻하지 않습니다.</p></div></div>{result?.registry?.state === 'SUCCESS' ? <><RegistrySummary models={models} /><RegistryTable models={models} permissions={permissions} actionPending={actionPending} onAction={runAction} /></> : statePanel(result?.registry, 'MODEL_METRICS_READ')}</section>{permissions.includes('MODEL_ARTIFACT_REGISTER') ? <p className="model-releases-limited">등록·업로드 입력 계약 없음 <small>민감 artifact reference 입력은 TASK-219의 안전한 표시 범위에 승인되지 않았습니다.</small></p> : null}{permissions.includes('MODEL_ROLLBACK') ? <section className="model-releases-rollback"><div><strong>복원</strong><p>source-defined rollback target만 사용합니다.</p></div><button type="button" disabled={Boolean(actionPending)} onClick={() => runAction('ROLLBACK')}>{actionPending === 'ROLLBACK:current' ? '처리 중' : '복원 요청'}</button></section> : null}{actionError ? <p role="alert" className="model-releases-action-error">작업 요청 실패: {actionError.code || 'MODEL_ACTION_FAILED'}</p> : null}<section className="model-releases-section" aria-labelledby="batches-heading"><div className="model-releases-heading"><div><h2 id="batches-heading">예측 배치</h2><p>batch modelVersion은 배치 메타데이터이며 runtime serving identity가 아닙니다.</p></div></div><Batches source={result?.batches} /></section><section className="model-releases-section" aria-labelledby="history-heading"><div className="model-releases-heading"><div><h2 id="history-heading">변경 이력</h2><p>privacy-safe audit source의 MODEL 대상 lifecycle 기록만 읽기 전용으로 표시합니다.</p></div></div>{result?.history?.state === 'SUCCESS' ? <History source={result.history} /> : statePanel(result?.history, 'AUDIT_READ')}</section></main>;
}
