package com.ddarungflow.modelops;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class ModelRuntimeRegistryMigrationTest {
    @Test
    void migratesLegacyRegisteredRowsAndEnforcesRuntimeImportedProvenance() {
        String url = "jdbc:h2:mem:model-runtime-v17-migration;MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        DriverManagerDataSource dataSource = new DriverManagerDataSource(url, "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
            CREATE TABLE model_artifacts (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              version varchar(100) NOT NULL UNIQUE,
              trainer_user_id bigint NOT NULL,
              artifact_key varchar(512) NOT NULL,
              sha256 varchar(64) NOT NULL UNIQUE,
              code_commit varchar(40) NOT NULL,
              data_manifest_hash varchar(64) NOT NULL,
              config_hash varchar(64) NOT NULL,
              feature_schema_version varchar(64) NOT NULL,
              manifest_key varchar(512),
              manifest_sha256 varchar(64),
              validated_by_user_id bigint,
              state varchar(20) NOT NULL,
              created_at timestamp(6) with time zone NOT NULL
            )
            """);
        jdbc.update("""
            INSERT INTO model_artifacts(version, trainer_user_id, artifact_key, sha256, code_commit,
              data_manifest_hash, config_hash, feature_schema_version, state, created_at)
            VALUES (?, 1, 'registered/model.bin', ?, 'abc123', ?, ?, 'v1', 'DRAFT', CURRENT_TIMESTAMP)
            """, "registered-v1", "a".repeat(64), "b".repeat(64), "c".repeat(64));

        Flyway flyway = Flyway.configure().dataSource(dataSource).locations("classpath:db/migration")
            .baselineOnMigrate(true).baselineVersion("16").target("17").load();
        flyway.migrate();

        assertThat(flyway.info().current().getVersion().getVersion()).isEqualTo("17");
        assertThat(jdbc.queryForObject(
            "SELECT source_origin FROM model_artifacts WHERE version = 'registered-v1'", String.class))
            .isEqualTo("REGISTERED");
        insertImported(jdbc, "imported-active", "d".repeat(64), "ACTIVE");
        insertImported(jdbc, "imported-retired", "e".repeat(64), "RETIRED");

        assertThatThrownBy(() -> jdbc.update("""
            INSERT INTO model_artifacts(version, trainer_user_id, artifact_key, sha256, code_commit,
              data_manifest_hash, config_hash, feature_schema_version, state, created_at, source_origin)
            VALUES ('mixed-import', 1, 'private/mixed.bin', ?, 'abc123', NULL, NULL, NULL,
              'ACTIVE', CURRENT_TIMESTAMP, 'RUNTIME_IMPORTED')
            """, "f".repeat(64))).isInstanceOf(RuntimeException.class);
        assertThatThrownBy(() -> insertImported(jdbc, "invalid-draft", "1".repeat(64), "DRAFT"))
            .isInstanceOf(RuntimeException.class);
    }

    private void insertImported(JdbcTemplate jdbc, String version, String sha, String state) {
        jdbc.update("""
            INSERT INTO model_artifacts(version, trainer_user_id, artifact_key, sha256, code_commit,
              data_manifest_hash, config_hash, feature_schema_version, manifest_key, manifest_sha256,
              state, created_at, source_origin)
            VALUES (?, NULL, 'private/model.bin', ?, NULL, NULL, NULL, NULL,
              'private/manifest.json', ?, ?, CURRENT_TIMESTAMP, 'RUNTIME_IMPORTED')
            """, version, sha, "9".repeat(64), state);
    }
}
