import { useEffect, useRef, useState } from 'react';
import { getCounterfactuals, getJourney, replanJourney, saveJourney } from './api/journeyApi';
import { toSaveRequest } from './contracts/journeyContracts';
import './JourneyPage.css';

const labels = { READY: '준비됨', PARTIAL: '부분 결과', CLARIFICATION_REQUIRED: '추가 확인 필요', UNAVAILABLE: '이용 불가', EXPIRED: '만료됨' };
const value = (source, keys) => keys.map((key) => source?.[key]).find((item) => item !== null && item !== undefined && item !== '');
function candidateRows(candidate) { return [['대여 가능성', value(candidate, ['rentalProbability', 'rentalProbabilityPercent'])], ['반납 가능성', value(candidate, ['returnProbability', 'returnProbabilityPercent'])], ['이동 시간', value(candidate, ['cyclingMinutes', 'journeyMinutes'])], ['거리', value(candidate, ['distanceMeters', 'distance'])]].filter(([, item]) => item !== undefined); }

export default function JourneyResultPage({ decisionId, onNavigate }) {
  const [state, setState] = useState({ type: 'loading' }); const [counterfactual, setCounterfactual] = useState(null); const [action, setAction] = useState(''); const requestToken = useRef(0);
  const load = async () => { const token = ++requestToken.current; setState({ type: 'loading' }); try { const decision = await getJourney(decisionId); if (token === requestToken.current) setState({ type: 'decision', decision }); } catch (error) { if (token === requestToken.current) setState({ type: error.status === 401 ? '401' : error.status === 404 ? '404' : error.status === 410 ? 'EXPIRED' : 'network', error }); } };
  useEffect(() => { load(); }, [decisionId]); // eslint-disable-line react-hooks/exhaustive-deps
  const replan = async () => { if (state.type !== 'decision') return; const token = ++requestToken.current; setAction('replan'); try { const next = await replanJourney(decisionId, { ...(state.decision.normalizedIntent || {}), expectedRevision: state.decision.revision }); if (token === requestToken.current) setState({ type: 'decision', decision: next }); } catch (error) { if (token === requestToken.current) setAction(error.code === 'JOURNEY_REVISION_CONFLICT' ? 'revision-conflict' : error.message); return; } if (token === requestToken.current) setAction(''); };
  const counterfactuals = async () => { if (state.type !== 'decision') return; try { setCounterfactual(await getCounterfactuals(decisionId)); } catch { setCounterfactual(null); } };
  const save = async () => { if (state.type !== 'decision') return; try { const idempotencyKey = window.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`; setAction('save'); await saveJourney(toSaveRequest(state.decision), idempotencyKey); setAction('saved'); } catch (error) { setAction(error.code === 'SAVED_ROUTE_LIMIT_REACHED' ? 'save-limit' : error.code === 'IDEMPOTENCY_CONFLICT' ? 'save-conflict' : error.message); } };
  if (state.type === 'loading') return <main className="journey-page"><p role="status">여정을 불러오는 중입니다.</p></main>;
  if (state.type !== 'decision') return <main className="journey-page"><section className="journey-unavailable" role="status"><h1>{state.type === '401' ? '로그인이 필요합니다' : state.type === '404' ? '여정을 찾을 수 없습니다' : state.type === 'EXPIRED' ? '여정이 만료되었습니다' : '네트워크 오류'}</h1><p>{state.type === 'network' ? '연결을 확인한 뒤 다시 시도해 주세요.' : '입력을 확인하고 새 여정을 만들어 주세요.'}</p></section><button onClick={() => onNavigate('journey')}>조건 다시 입력</button></main>;
  const { decision } = state; const status = decision.status || 'UNAVAILABLE';
  return <main className="journey-page"><section className="journey-hero"><p>UI-25 · Journey Result</p><h1>{labels[status] || status}</h1>{decision.clarification && <p role="status">{decision.clarification.question || decision.clarification}</p>}</section>{status === 'UNAVAILABLE' || status === 'EXPIRED' ? <section className="journey-unavailable" role="status"><h2>{status}</h2><p>{decision.warnings?.join(' ') || '새 조건으로 다시 시도해 주세요.'}</p></section> : <><section className="journey-candidates">{(decision.candidates || []).map((candidate) => <article key={candidate.candidateId}><h2>{candidate.archetype || candidate.candidateId}</h2><p>{candidate.advantage || candidate.advantages}</p><dl>{candidateRows(candidate).map(([label, item]) => <div key={label}><dt>{label}</dt><dd>{typeof item === 'number' && label.includes('가능성') ? `${item}%` : item}</dd></div>)}</dl>{candidate.unavailableFields?.length > 0 && <p>미제공: {candidate.unavailableFields.join(', ')}</p>}<p>{candidate.tradeoff || candidate.tradeoffs}</p></article>)}</section>{status === 'PARTIAL' && <p role="status" className="journey-notice">부분 결과입니다. {decision.warnings?.join(' ')}</p>}<section>{decision.provenance && <p>{decision.provenance.dataAsOf && `기준시각: ${decision.provenance.dataAsOf}`}{decision.provenance.model && ` · 모델: ${decision.provenance.model}`}{decision.provenance.provider && ` · 제공자: ${decision.provenance.provider}`}</p>}</section><div className="journey-actions"><button onClick={replan} disabled={action === 'replan'}>재계획</button><button onClick={counterfactuals}>조건 비교</button><button onClick={save}>저장</button></div>{action === 'revision-conflict' && <p role="alert">다른 재계획 결과가 있습니다. 다시 불러와 주세요.</p>}{action === 'saved' && <p role="status">저장했습니다.</p>}{action === 'save-limit' && <p role="alert">저장 여정은 최대 10개입니다.</p>}{action === 'save-conflict' && <p role="alert">저장 요청이 충돌했습니다.</p>}{counterfactual && <section className="journey-map"><h2>조건 비교</h2><p>{counterfactual.summary || counterfactual.message}</p></section>}</>}<button onClick={() => onNavigate('journey')}>조건 다시 입력</button></main>;
}
