import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import JourneyResultPage from './JourneyResultPage';
import { getJourney, replanJourney, saveJourney } from './api/journeyApi';
jest.mock('./api/journeyApi', () => ({ getJourney: jest.fn(), replanJourney: jest.fn(), getCounterfactuals: jest.fn(), saveJourney: jest.fn() }));

const coreCandidate = { candidateId: 'station-1', rank: 1, archetype: 'CORE_RENTAL', stationName: '서울숲역 1번 출구', rentalProbability: 0.82, returnProbability: 70, cyclingMinutes: 14, elevationMeters: 25, bikeLanePercent: 45, availableBikeCount: 8, requiredBikeCount: 2, accessDurationSeconds: 421, distanceMeters: 450, arrivalAt: '2026-08-28T15:42:00+09:00', inventoryCollectedAt: '2026-08-28T15:10:00+09:00', availabilityLevel: 'HIGH' };
const decision = (status = 'READY') => ({ decisionId: 'd1', revision: 1, status, normalizedIntent: { requestMode: 'FORM', origin: { placeId: 'o', displayName: '출발', latitude: 37.54, longitude: 127.05 }, destination: { placeId: 'd', displayName: '도착', latitude: 37.55, longitude: 127.06 }, departureAt: '2026-08-28T22:00:00.000Z', requiredBikeCount: 2, maxJourneyMinutes: 60, preferences: { lowSlope: 'MEDIUM' }, avoid: [] }, candidates: [coreCandidate], provenance: { dataAsOf: '2026-08-28T10:00:00+09:00' } });
beforeEach(() => jest.clearAllMocks());

test('shows real Core rental fields and hides deferred and internal fields', async () => { getJourney.mockResolvedValue(decision()); render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await screen.findByText('서울숲역 1번 출구'); expect(screen.getByText('추천 1')).toBeInTheDocument(); ['대여 가능성', '현재 자전거', '필요 자전거', '대여소까지 도보', '거리', '예상 도착', '재고 기준'].forEach((text) => expect(screen.getByText(text)).toBeInTheDocument()); expect(screen.getByText('82%')).toBeInTheDocument(); expect(screen.getByText('8대')).toBeInTheDocument(); expect(screen.getByText('2대')).toBeInTheDocument(); expect(screen.getByText('약 8분')).toBeInTheDocument(); expect(screen.getByText('450m')).toBeInTheDocument(); expect(screen.getByText('높음')).toBeInTheDocument(); expect(screen.queryByText('CORE_RENTAL')).not.toBeInTheDocument(); expect(screen.queryByText('조건 비교')).not.toBeInTheDocument(); ['반납 가능성', '이동 시간', 'returnProbability', 'cyclingMinutes', 'elevationMeters', 'bikeLanePercent'].forEach((text) => expect(screen.queryByText(text)).not.toBeInTheDocument()); });
test('does not turn a null probability into zero', async () => { getJourney.mockResolvedValue({ ...decision(), candidates: [{ ...coreCandidate, rentalProbability: null }] }); render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await screen.findByText('서울숲역 1번 출구'); expect(screen.queryByText('0%')).not.toBeInTheDocument(); expect(screen.queryByText('대여 가능성')).not.toBeInTheDocument(); });
test.each(['CLARIFICATION_REQUIRED', 'PARTIAL', 'UNAVAILABLE', 'EXPIRED'])('shows a Korean %s state without technical warning codes', async (status) => { const current = decision(status); if (status === 'CLARIFICATION_REQUIRED') { current.normalizedIntent.destination = null; current.clarification = { question: '추가 조건', missingFields: ['destination'] }; } getJourney.mockResolvedValue(current); render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await waitFor(() => expect(screen.getByText(status === 'PARTIAL' ? '일부 추천 결과' : status === 'UNAVAILABLE' ? '이용 불가' : status === 'EXPIRED' ? '만료됨' : '추가 확인 필요')).toBeInTheDocument()); if (status === 'CLARIFICATION_REQUIRED') expect(screen.getByRole('status')).toHaveTextContent('목적지를 검색 결과에서 선택'); expect(screen.queryByText('JOURNEY_RENTAL_PARTIAL')).not.toBeInTheDocument(); });
test.each([[401, '로그인이 필요합니다'], [404, '여정을 찾을 수 없습니다'], [410, '여정이 만료되었습니다'], [undefined, '네트워크 오류']])('shows a user-facing failure for %s', async (status, message) => { getJourney.mockRejectedValue({ status }); render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await screen.findByText(message); expect(screen.getByRole('button', { name: '조건 다시 입력' })).toBeInTheDocument(); });
test('blocks a no-change replan without an API call', async () => { getJourney.mockResolvedValue(decision()); render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await screen.findByText('서울숲역 1번 출구'); fireEvent.click(screen.getByText('재계획')); expect(replanJourney).not.toHaveBeenCalled(); expect(screen.getByRole('status')).toHaveTextContent('변경된 조건이 없습니다'); });
test('replans changed values as a structured FORM request without natural language', async () => { const naturalLanguageDecision = { ...decision(), normalizedIntent: { ...decision().normalizedIntent, requestMode: 'NATURAL_LANGUAGE' } }; const revised = { ...naturalLanguageDecision, revision: 2, normalizedIntent: { ...naturalLanguageDecision.normalizedIntent, requestMode: 'FORM', requiredBikeCount: 4 } }; getJourney.mockResolvedValue(naturalLanguageDecision); replanJourney.mockResolvedValue(revised); render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await screen.findByText('서울숲역 1번 출구'); fireEvent.change(screen.getByLabelText('재계획 필요한 자전거 수'), { target: { value: '4' } }); fireEvent.click(screen.getByText('재계획')); await waitFor(() => expect(replanJourney).toHaveBeenCalledWith('d1', expect.objectContaining({ requestMode: 'FORM', requiredBikeCount: 4, expectedRevision: 1, origin: naturalLanguageDecision.normalizedIntent.origin, destination: naturalLanguageDecision.normalizedIntent.destination }))); expect(replanJourney.mock.calls[0][1]).not.toHaveProperty('naturalLanguageText'); await waitFor(() => expect(screen.getByLabelText('재계획 필요한 자전거 수')).toHaveValue(4)); });
test('replans when only departure time changes', async () => { getJourney.mockResolvedValue(decision()); replanJourney.mockResolvedValue({ ...decision(), revision: 2 }); render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await screen.findByText('서울숲역 1번 출구'); fireEvent.change(screen.getByLabelText('재계획 출발 희망 시각'), { target: { value: '2026-08-29T09:00' } }); fireEvent.click(screen.getByText('재계획')); await waitFor(() => expect(replanJourney).toHaveBeenCalledWith('d1', expect.objectContaining({ requestMode: 'FORM', departureAt: new Date('2026-08-29T09:00').toISOString(), expectedRevision: 1 }))); });
test('keeps a newer loaded decision when an older replan response arrives late', async () => { let resolveReplan; getJourney.mockResolvedValueOnce(decision()).mockResolvedValueOnce({ ...decision(), decisionId: 'd2', revision: 3, normalizedIntent: { ...decision().normalizedIntent, requiredBikeCount: 5 } }); replanJourney.mockImplementation(() => new Promise((resolve) => { resolveReplan = resolve; })); const { rerender } = render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await screen.findByText('서울숲역 1번 출구'); fireEvent.change(screen.getByLabelText('재계획 필요한 자전거 수'), { target: { value: '3' } }); fireEvent.click(screen.getByText('재계획')); rerender(<JourneyResultPage decisionId="d2" onNavigate={jest.fn()} />); await waitFor(() => expect(screen.getByLabelText('재계획 필요한 자전거 수')).toHaveValue(5)); await act(async () => { resolveReplan({ ...decision(), revision: 2, normalizedIntent: { ...decision().normalizedIntent, requiredBikeCount: 3 } }); }); expect(screen.getByLabelText('재계획 필요한 자전거 수')).toHaveValue(5); });
test('keeps replan revision conflict and save behavior', async () => { getJourney.mockResolvedValue(decision()); saveJourney.mockResolvedValue({}); render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await screen.findByText('서울숲역 1번 출구'); replanJourney.mockRejectedValue({ code: 'JOURNEY_REVISION_CONFLICT' }); fireEvent.change(screen.getByLabelText('재계획 필요한 자전거 수'), { target: { value: '3' } }); await act(async () => { screen.getByText('재계획').click(); }); await screen.findByRole('alert'); expect(screen.getByRole('alert')).toHaveTextContent('다른 재계획'); await act(async () => { screen.getByText('저장').click(); }); await waitFor(() => expect(saveJourney).toHaveBeenCalledWith(expect.objectContaining({ destination: expect.anything(), origin: expect.anything() }), expect.any(String))); });
