import { act, render, screen, waitFor } from '@testing-library/react';
import JourneyResultPage from './JourneyResultPage';
import { getJourney, replanJourney, saveJourney } from './api/journeyApi';
jest.mock('./api/journeyApi', () => ({ getJourney: jest.fn(), replanJourney: jest.fn(), getCounterfactuals: jest.fn(), saveJourney: jest.fn() }));

const coreCandidate = { candidateId: 'station-1', rank: 1, archetype: 'CORE_RENTAL', stationName: '서울숲역 1번 출구', rentalProbability: 0.82, returnProbability: 70, cyclingMinutes: 14, elevationMeters: 25, bikeLanePercent: 45, availableBikeCount: 8, requiredBikeCount: 2, accessDurationSeconds: 421, distanceMeters: 450, arrivalAt: '2026-08-28T15:42:00+09:00', inventoryCollectedAt: '2026-08-28T15:10:00+09:00', availabilityLevel: 'HIGH' };
const decision = (status = 'READY') => ({ decisionId: 'd1', revision: 1, status, normalizedIntent: { origin: { placeId: 'o', displayName: '출발' }, destination: { placeId: 'd', displayName: '도착' }, requiredBikeCount: 2, maxJourneyMinutes: 60 }, candidates: [coreCandidate], provenance: { dataAsOf: '2026-08-28T10:00:00+09:00' } });
beforeEach(() => jest.clearAllMocks());

test('shows real Core rental fields and hides deferred and internal fields', async () => { getJourney.mockResolvedValue(decision()); render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await screen.findByText('서울숲역 1번 출구'); expect(screen.getByText('추천 1')).toBeInTheDocument(); ['대여 가능성', '현재 자전거', '필요 자전거', '대여소까지 도보', '거리', '예상 도착', '재고 기준'].forEach((text) => expect(screen.getByText(text)).toBeInTheDocument()); expect(screen.getByText('82%')).toBeInTheDocument(); expect(screen.getByText('8대')).toBeInTheDocument(); expect(screen.getByText('2대')).toBeInTheDocument(); expect(screen.getByText('약 8분')).toBeInTheDocument(); expect(screen.getByText('450m')).toBeInTheDocument(); expect(screen.getByText('높음')).toBeInTheDocument(); expect(screen.queryByText('CORE_RENTAL')).not.toBeInTheDocument(); expect(screen.queryByText('조건 비교')).not.toBeInTheDocument(); ['반납 가능성', '이동 시간', 'returnProbability', 'cyclingMinutes', 'elevationMeters', 'bikeLanePercent'].forEach((text) => expect(screen.queryByText(text)).not.toBeInTheDocument()); });
test('does not turn a null probability into zero', async () => { getJourney.mockResolvedValue({ ...decision(), candidates: [{ ...coreCandidate, rentalProbability: null }] }); render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await screen.findByText('서울숲역 1번 출구'); expect(screen.queryByText('0%')).not.toBeInTheDocument(); expect(screen.queryByText('대여 가능성')).not.toBeInTheDocument(); });
test.each(['CLARIFICATION_REQUIRED', 'PARTIAL', 'UNAVAILABLE', 'EXPIRED'])('shows a Korean %s state without technical warning codes', async (status) => { const current = decision(status); if (status === 'CLARIFICATION_REQUIRED') { current.normalizedIntent.destination = null; current.clarification = { question: '추가 조건', missingFields: ['destination'] }; } getJourney.mockResolvedValue(current); render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await waitFor(() => expect(screen.getByText(status === 'PARTIAL' ? '일부 추천 결과' : status === 'UNAVAILABLE' ? '이용 불가' : status === 'EXPIRED' ? '만료됨' : '추가 확인 필요')).toBeInTheDocument()); if (status === 'CLARIFICATION_REQUIRED') expect(screen.getByRole('status')).toHaveTextContent('목적지를 검색 결과에서 선택'); expect(screen.queryByText('JOURNEY_RENTAL_PARTIAL')).not.toBeInTheDocument(); });
test.each([[401, '로그인이 필요합니다'], [404, '여정을 찾을 수 없습니다'], [410, '여정이 만료되었습니다'], [undefined, '네트워크 오류']])('shows a user-facing failure for %s', async (status, message) => { getJourney.mockRejectedValue({ status }); render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await screen.findByText(message); expect(screen.getByRole('button', { name: '조건 다시 입력' })).toBeInTheDocument(); });
test('keeps replan revision conflict and save behavior', async () => { getJourney.mockResolvedValue(decision()); saveJourney.mockResolvedValue({}); render(<JourneyResultPage decisionId="d1" onNavigate={jest.fn()} />); await screen.findByText('서울숲역 1번 출구'); replanJourney.mockRejectedValue({ code: 'JOURNEY_REVISION_CONFLICT' }); await act(async () => { screen.getByText('재계획').click(); }); await screen.findByRole('alert'); expect(screen.getByRole('alert')).toHaveTextContent('다른 재계획'); await act(async () => { screen.getByText('저장').click(); }); await waitFor(() => expect(saveJourney).toHaveBeenCalledWith(expect.objectContaining({ destination: expect.anything(), origin: expect.anything() }), expect.any(String))); });
