import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import JourneyPlannerPage from './JourneyPlannerPage';
import { planJourney, searchJourneyPlaces } from './api/journeyApi';
jest.mock('./api/journeyApi', () => ({ planJourney: jest.fn(), searchJourneyPlaces: jest.fn() }));

const place = { placeId: 'kakao-1', displayName: '성수역', latitude: 37.544, longitude: 127.056 };
beforeEach(() => { sessionStorage.clear(); jest.clearAllMocks(); jest.spyOn(Date, 'now').mockReturnValue(new Date('2026-08-28T12:00:00Z').getTime()); searchJourneyPlaces.mockResolvedValue([place]); });
afterEach(() => Date.now.mockRestore());
async function selectOrigin() { fireEvent.change(screen.getByLabelText('출발 장소'), { target: { value: '성수' } }); await screen.findByRole('button', { name: '성수역' }); fireEvent.click(screen.getByRole('button', { name: '성수역' })); }
function setFutureDeparture() { fireEvent.change(screen.getByLabelText('출발 희망 시각'), { target: { value: '2026-08-28T22:00' } }); }
function setFutureDepartureWithInput() { fireEvent.input(screen.getByLabelText('출발 희망 시각'), { target: { value: '2026-08-28T22:00' } }); }
test('keeps input and asks anonymous users to log in without automatic execution', async () => { render(<JourneyPlannerPage authState="anonymous" onNavigate={jest.fn()} />); await selectOrigin(); setFutureDeparture(); fireEvent.click(screen.getByRole('button',{name:'여정 만들기'})); expect(screen.getByRole('status')).toHaveTextContent('입력을 보존'); expect(planJourney).not.toHaveBeenCalled(); expect(sessionStorage.getItem('ddarung.journey.planner-input')).toContain('kakao-1'); });
test('restores input but does not plan after login until the user submits', () => { sessionStorage.setItem('ddarung.journey.planner-input', JSON.stringify({ origin: place, departureAt: '2026-08-28T22:00' })); render(<JourneyPlannerPage authState="authenticated" onNavigate={jest.fn()} />); expect(screen.getByLabelText('출발 장소')).toHaveValue('성수역'); expect(planJourney).not.toHaveBeenCalled(); });
test('does not plan for raw search text, missing departure time, or a past departure time', async () => { render(<JourneyPlannerPage authState="authenticated" onNavigate={jest.fn()} />); fireEvent.change(screen.getByLabelText('출발 장소'), { target: { value: '성수' } }); fireEvent.click(screen.getByRole('button',{name:'여정 만들기'})); expect(planJourney).not.toHaveBeenCalled(); await selectOrigin(); fireEvent.click(screen.getByRole('button',{name:'여정 만들기'})); expect(screen.getByRole('status')).toHaveTextContent('출발 희망 시각'); fireEvent.change(screen.getByLabelText('출발 희망 시각'), { target: { value: '2026-08-28T10:00' } }); fireEvent.click(screen.getByRole('button',{name:'여정 만들기'})); expect(screen.getByRole('status')).toHaveTextContent('현재 이후'); expect(planJourney).not.toHaveBeenCalled(); });
test('sends a selected place, nullable destination, offset-aware departure time, and actual decisionId', async () => { planJourney.mockResolvedValue({ decisionId: 'actual-id' }); const onNavigate=jest.fn(); render(<JourneyPlannerPage authState="authenticated" onNavigate={onNavigate} />); await selectOrigin(); setFutureDeparture(); fireEvent.change(screen.getByLabelText('필요한 자전거 수'), { target: { value: '5' } }); fireEvent.click(screen.getByRole('button',{name:'여정 만들기'})); await waitFor(() => expect(onNavigate).toHaveBeenCalledWith('journey-result','actual-id')); expect(planJourney).toHaveBeenCalledWith(expect.objectContaining({ origin: place, destination: null, requiredBikeCount: 5, maxJourneyMinutes: 60, departureAt: expect.stringMatching(/(Z|[+-]\d\d:\d\d)$/) })); });
test('submits a natural-language journey after a native input event', async () => { planJourney.mockResolvedValue({ decisionId: 'input-event-id' }); render(<JourneyPlannerPage authState="authenticated" onNavigate={jest.fn()} />); await selectOrigin(); fireEvent.change(screen.getByLabelText('입력 방식'), { target: { value: 'NATURAL_LANGUAGE' } }); fireEvent.change(screen.getByLabelText('자연어 요청'), { target: { value: '한강 쪽으로 가고 싶어' } }); setFutureDepartureWithInput(); fireEvent.click(screen.getByRole('button',{name:'여정 만들기'})); await waitFor(() => expect(planJourney).toHaveBeenCalledWith(expect.objectContaining({ requestMode: 'NATURAL_LANGUAGE', naturalLanguageText: '한강 쪽으로 가고 싶어', departureAt: expect.stringMatching(/(Z|[+-]\d\d:\d\d)$/) }))); });
test('uses the native datetime control value when React state is stale', async () => { planJourney.mockResolvedValue({ decisionId: 'native-value-id' }); render(<JourneyPlannerPage authState="authenticated" onNavigate={jest.fn()} />); await selectOrigin(); const departure = screen.getByLabelText('출발 희망 시각'); departure.value = '2026-08-28T22:00'; fireEvent.click(screen.getByRole('button',{name:'여정 만들기'})); await waitFor(() => expect(planJourney).toHaveBeenCalledWith(expect.objectContaining({ departureAt: expect.stringMatching(/(Z|[+-]\d\d:\d\d)$/) }))); });
test('invalidates a selected place after its search text changes', async () => { render(<JourneyPlannerPage authState="authenticated" onNavigate={jest.fn()} />); await selectOrigin(); fireEvent.change(screen.getByLabelText('출발 장소'), { target: { value: '성수역 새 검색' } }); setFutureDeparture(); fireEvent.click(screen.getByRole('button',{name:'여정 만들기'})); expect(planJourney).not.toHaveBeenCalled(); expect(screen.getByRole('status')).toHaveTextContent('검색 결과에서 선택'); });
