import { useEffect, useState } from "react";
import AppHeader from "../../shared/AppHeader";
import { createQuestion, getQuestion, listQuestions } from "./api/qnaApi";
import QnaPagination from "./components/QnaPagination";
import QnaQuestionDetail from "./components/QnaQuestionDetail";
import QnaQuestionForm from "./components/QnaQuestionForm";
import QnaQuestionList from "./components/QnaQuestionList";
import QnaSearchFilters from "./components/QnaSearchFilters";
import "./QnaPage.css";

export default function QnaPage({ authState, user, onNavigate, onLogout }) {
  const [questions, setQuestions] = useState([]); const [view, setView] = useState("list"); const [selectedQuestion, setSelectedQuestion] = useState(null); const [query, setQuery] = useState(""); const [submittedQuery, setSubmittedQuery] = useState(""); const [category, setCategory] = useState("ALL"); const [answerStatus, setAnswerStatus] = useState("ALL"); const [tab, setTab] = useState("all"); const [page, setPage] = useState(1); const [state, setState] = useState("loading");
  const load = () => { if (authState !== "authenticated") { setState(authState === "loading" ? "loading" : "auth-required"); return; } setState("loading"); listQuestions({ scope: tab === "mine" ? "MINE" : "PUBLIC", query: submittedQuery, category, status: answerStatus === "OPEN" ? "PENDING" : answerStatus, page: page - 1 }).then(({ items }) => { setQuestions(items); setState(items.length ? "success" : "empty"); }).catch((error) => setState(error.status === 401 ? "auth-required" : "error")); };
  useEffect(load, [authState, tab, submittedQuery, category, answerStatus, page]);
  const changeFilter = (setter, value) => { setter(value); setPage(1); };
  const submitQuestion = async (question) => { try { await createQuestion({ title: question.title, body: question.body, category: question.category, visibility: question.visibility }); setTab("mine"); setPage(1); setView("list"); } catch (error) { setState(error.status === 401 ? "auth-required" : "error"); setView("list"); } };
  const content = state === "loading" ? <p>불러오는 중입니다.</p> : state === "auth-required" ? <p>로그인이 필요합니다.</p> : state === "error" ? <section aria-live="polite"><p>질문을 표시할 수 없습니다.</p><button onClick={load}>다시 시도</button></section> : <><QnaQuestionList questions={questions} onSelect={(question) => getQuestion(question.id).then((item) => { setSelectedQuestion(item); setView("detail"); }).catch((error) => setState(error.status === 401 ? "auth-required" : "error"))} /><QnaPagination page={page} onChange={setPage} /></>;
  return <div className="qna-shell"><AppHeader activeRoute="qna" authState={authState} user={user} onNavigate={onNavigate} onLogout={onLogout} /><main className="qna-content">{view === "create" ? <QnaQuestionForm onCancel={() => setView("list")} onCreate={submitQuestion} /> : view === "detail" && selectedQuestion ? <QnaQuestionDetail question={selectedQuestion} onBack={() => setView("list")} /> : <><section className="qna-title-row"><div><h1>Q&amp;A</h1><p>서비스 이용과 예측 결과에 관해 궁금한 점을 확인하세요.</p></div><button className="qna-write" type="button" onClick={() => setView("create")}>질문 작성</button></section><QnaSearchFilters query={query} category={category} answerStatus={answerStatus} onQueryChange={setQuery} onCategoryChange={(value) => changeFilter(setCategory, value)} onAnswerStatusChange={(value) => changeFilter(setAnswerStatus, value)} onSubmit={(event) => { event.preventDefault(); setSubmittedQuery(query.trim()); setPage(1); }} /><div className="qna-tabs" role="tablist" aria-label="질문 범위"><button role="tab" aria-selected={tab === "all"} className={tab === "all" ? "active" : ""} type="button" onClick={() => changeFilter(setTab, "all")}>전체 질문</button><button role="tab" aria-selected={tab === "mine"} className={tab === "mine" ? "active" : ""} type="button" onClick={() => changeFilter(setTab, "mine")}>내 질문</button></div>{content}</>}</main></div>;
}
