package com.ddarungflow.journey.ai;

public enum JourneyAiErrorCode {
    AI_DISABLED,
    AI_PROVIDER_UNAVAILABLE,
    AI_PROVIDER_REFUSAL,
    AI_RESPONSE_INCOMPLETE,
    AI_OUTPUT_SCHEMA_INVALID,
    AI_TOOL_NOT_ALLOWED,
    AI_TOOL_ARGUMENT_INVALID,
    AI_TOOL_VALUE_MISMATCH,
    AI_PII_BLOCKED
}
